export const defaultThemes: DefaultTheme[] = [
    {
        title: "Dark",
        thumbnailImgSrc: "/images/df-theme-1.png",
        sectionDetails: { title: "default", index: 0 },
        styling: {
            isDark: true,
            bg1: "#121112",
            bg2: "#141314",
            bg3: "#1d1d1d",
            fgColor1: "163, 182, 255",
            fgColor2: "163, 182, 255",
            textColor1: "255, 255, 255",
            textColor2: "12, 11, 12",
            lightColor: "#1b1b1c",
            lightColor2: "#1a1a1c",
            lightColor3: "#1e1e1e",
            modalBgColor: "#0B0B0B",
            modalBgAccentColor: "#131214",
            muiscPlayerBgColor: "rgba(50, 50, 50, 0.45)",
            musicProgressFgColor: "",
            navBtnColor: "none",
            navBtnBgColor: "#1A171A",
            navMenuBgColor: "#171617",
            navMenuBorder: "",
            minNavBtnColor: "#292221",
            minNavBtnBgColor: "#1d1c1f",
            sessionBlockColor: "#1e1e1e",
            bentoBoxBgColor: "#121213",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            rightBarBgColor: "#171617",
            elemColor1: "#6bb0f4",
            elemColor2: "#232323",
            elemTextColor: "#FFFFFF",
            cardBgColor: "#171617",
            cardHovColor: "#1a191a"
        }
    } as DefaultTheme,
    {
        title: "Light",
        thumbnailImgSrc: "dfImage2",
        sectionDetails: { title: "default", index: 1 },
        styling: {
            isDark: false,
            bg1: "#FFFDFA",
            bg2: "#ffffff",
            bg3: "#ffffff",
            fgColor1: "163, 182, 255",
            fgColor2: "163, 182, 255",
            textColor1: "23, 20, 18",
            textColor2: "255, 255, 255",
            lightColor: "#F8F5F1",
            lightColor2: "#F4F1EC",
            lightColor3: "#EAE7E2",
            modalBgColor: "#FBFBFB",
            modalBgAccentColor: "#f5f5f5",
            bentoBoxBgColor: "#FFFFFF",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 7px 0px rgba(0, 0, 0, 0.05)",
            muiscPlayerBgColor: "#A3B6FF",
            musicProgressFgColor: "",
            sessionBlockColor: "#f5f2f2",
            navMenuBgColor: "#F9F7F0",
            navBtnBgColor: "#e9e9e4",
            navBtnColor: "#3B3B3B",
            navMenuBorder: "1.5px solid rgba(0, 0, 0, 0.05)",
            minNavBtnColor: "#292221",
            minNavBtnBgColor: "#f1f0ea",
            rightBarBgColor: "#FFFDF9",
            elemColor1: "#6bb0f4",
            elemColor2: "#6bb0f4",
            elemTextColor: "#FFFFFF",
            cardBgColor: "#fffefc",
            cardHovColor: "#ffffff"
        }
    } as DefaultTheme
]

export const lightColorThemes: ColorTheme[] = [
    {
        title: "Sand",
        sectionDetails: { title: "light", index: 0 },
        colorPalette: [
            "#2E2B26", "#838368", "#B0AC92", "#EFE3C9", "#FEF6E7"
        ],
        styling: {
            isDark: false,
            bg1: "#fef7eb",
            bg2: "#FBF7E9",
            bg3: "#fefaf3",
            fgColor1: "55, 46, 23",
            fgColor2: "255, 255, 255",
            textColor1: "34, 28, 13",
            textColor2: "255, 255, 255",
            lightColor: "#f3ecdf",
            lightColor2: "#f3ecde",
            lightColor3: "#EEE6D4",
            modalBgColor: "#F5F0DF",
            modalBgAccentColor: "#EFEBDD",
            bentoBoxBgColor: "#FBF7E9",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#A09471",
            musicProgressFgColor: "",
            sessionBlockColor: "#eee8dc",
            navMenuBgColor: "#f8f1e4",
            navBtnColor: "#393528",
            navBtnBgColor: "#eee7d7",
            navMenuBorder: "1.5px solid rgba(0, 0, 0, 0.03)",
            minNavBtnColor: "#292221",
            minNavBtnBgColor: "#efeada",
            rightBarBgColor: "#f8f2e6",
            elemColor1: "#ABAA7C",
            elemColor2: "#ABAA7C",
            elemTextColor: "#FFFFFF",
            cardBgColor: "#FEFAF3",
            cardHovColor: "#fffcf8"
        }
    },
    {
        title: "Terracotta",
        sectionDetails: { title: "light", index: 1 },
        colorPalette: [
            "#2E2C29", "#7E766B", "#9B9280", "#DDD7CA", "#F1EBE1"
        ],
        styling: {
            isDark: false,
            bg1: "#e2ddd6",
            bg2: "#FBF7E9",
            bg3: "#efeeeb",
            fgColor1: "55, 46, 23",
            fgColor2: "255, 255, 255",
            textColor1: "29, 25, 19",
            textColor2: "255, 255, 255",
            lightColor: "#d9d5ce",
            lightColor2: "#d9d5ce",
            lightColor3: "#D1CBC0",
            modalBgColor: "#F5F0DF",
            modalBgAccentColor: "#EFEBDD",
            bentoBoxBgColor: "#FBF7E9",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#A09471",
            musicProgressFgColor: "",
            sessionBlockColor: "#d3cec6",
            navMenuBgColor: "#dbd5cb",
            navBtnColor: "#38352A",
            navBtnBgColor: "#d1cbc1",
            navMenuBorder: "1.5px solid rgba(0, 0, 0, 0.03)",
            minNavBtnColor: "#292221",
            minNavBtnBgColor: "#d1cdc5",
            rightBarBgColor: "#dcd7d0",
            elemColor1: "#A99F90",
            elemColor2: "#A99F90",
            elemTextColor: "#fdf9f3",
            cardBgColor: "#E9E6E0",
            cardHovColor: "#edeae6"
        }
    },
]

export const darkColorThemes: ColorTheme[] = [
    {
        title: "Adobe",
        sectionDetails: { title: "dark", index: 0 },
        colorPalette: ["#231C1C", "#312928", "#D5A4A4", "#F1CDB8", "#FFF5EC"],
        styling: {
            isDark: true,
            bg1: "#161313",
            bg2: "#131012",
            bg3: "#1d1b1a",
            fgColor1: "228, 188, 150",
            fgColor2: "228, 188, 150",
            textColor1: "255, 255, 255",
            textColor2: "30, 30, 30",
            lightColor: "#1f1c1c",
            lightColor2: "#201c1b",
            lightColor3: "#241E1E",
            modalBgColor: "#0c0a0c",
            modalBgAccentColor: "#100D0F",
            bentoBoxBgColor: "#110e10",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            muiscPlayerBgColor: "rgba(32, 28, 31, 0.43)",
            musicProgressFgColor: "",
            sessionBlockColor: "#211f1e",
            navMenuBgColor: "#1D1A19",
            navBtnColor: "#ffbfbf",
            navBtnBgColor: "#292221",
            minNavBtnColor: "#A47A7A",
            minNavBtnBgColor: "#25201F",
            navMenuBorder: "",
            rightBarBgColor: "#181615",
            elemColor1: "#F0BB9D",
            elemColor2: "#bf9090",
            elemTextColor: "#181417",
            cardBgColor: "#1A1717",
            cardHovColor: "#1d1a1a"
        }
    },
    {
        title: "Gotham",
        sectionDetails: { title: "dark", index: 1 },
        colorPalette: ["#1A1A22", "#312E3C", "#B6ABC7", "#F8CEB6", "#FFF5EC"],
        styling: {
            isDark: true,
            bg1: "#141418",
            bg2: "#0E0D11",
            bg3: "#1e1e23",
            fgColor1: "255, 255, 255",
            fgColor2: "228, 188, 150",
            textColor1: "255, 255, 255",
            textColor2: "30, 30, 30",
            lightColor: "#1b1b20",
            lightColor2: "#1b1b20",
            lightColor3: "#232325",
            modalBgColor: "#0c0a0c",
            modalBgAccentColor: "#100D0F",
            bentoBoxBgColor: "#110e10",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            muiscPlayerBgColor: "rgba(32, 28, 31, 0.43)",
            musicProgressFgColor: "",
            sessionBlockColor: "#232327",
            navMenuBgColor: "#18181c",
            navBtnColor: "#cdb1fa",
            navBtnBgColor: "#1f1f27",
            minNavBtnColor: "#A47A7A",
            minNavBtnBgColor: "#1d1d25",
            navMenuBorder: "",
            rightBarBgColor: "#18181c",
            elemColor1: "#F2C59C",
            elemColor2: "#F2C59C",
            elemTextColor: "#0E0D11",
            cardBgColor: "#19191D",
            cardHovColor: "#1d1d22"
        }
    }
]