const ytRecsPlaylists: { title: string, playlists: YoutubePlaylist[] }[] = [
    {
        title: "Lofi / Chill",
        playlists: [
            {
                id: "PLDbJgJ7-hEUXmQoTwvsqGPshb2cPopUKi",
                title: "Lofi Girl - Compilations",
                description: "Curated compilation of Lofi Girl's beloved and soothing videos for ultimate relaxation and chill vibes.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Lofi Girl",
                thumbnailURL: "https://i.ytimg.com/vi/zFhfksjf_mY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQgYKl48s3nIAYnxSDbiy65PL42g",
                channelImgSrc: "https://yt3.googleusercontent.com/gY8H7K-3Eg3olVftRBiqqFe-N5d9Rx90jAsrfQuxDa4m32Wm-kWK6AQJhwchvYLf-H4EjGhCSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@LofiGirl",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvIY2AHFkx07G2tBQcW6oTm3",
                title: "Studio Ghibli Music",
                description: "The magic of Studio Ghibli, mixed into a visual & sonic experience.",
                vidCount: 14,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/Sx4xVyXHl60/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAyg77XoyF7_I9aONds6qEiFhDD4g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLDZkhQggdz7bx5VWWi-kKA",
                title: "Romantic Chill",
                description: "For the romantics of the classical / dark-academia aesthetics.",
                vidCount: 21,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/Y56ODjb8ZMo/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCK4yCIusXl4LoiDrvIxqq9C5RunA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLUAsF5s_xnHtw0CAoHTYDESe9o2BKCRIN",
                title: "The Jazz Hop Café - Mixes",
                description: "Explore a captivating collection of lo-fi and jazz playlists, perfect for cozy moments and relaxing vibes.",
                vidCount: 108,
                channelId: "",
                channelTitle: "The Jazz Hop Café",
                thumbnailURL: "https://i.ytimg.com/vi/TYCBicKyVhs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAxH2OcNzH6KHMd839rWzwG0r8koA",
                channelImgSrc: "https://yt3.ggpht.com/WqdmWxOq6FRiTtaz8u4evDCz_Dh5zN8OjlY0rGLBIHPdmx-mk8HoIA3y87RGOM9a8HJnec074pw=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheJazzHopCafe",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvK4MCsYvLENDGlej8mentJ-",
                title: "Gaming Relax & Chill",
                description: "Escape into tranquility with melodies from Zelda, Animal Crossing, and other Nintendo favorites in this calming playlist.",
                vidCount: 22,
                channelId: "",
                channelTitle: "Mutliple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/EdHGrnuCEo4/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhdIGUoUTAP&rs=AOn4CLCRjy5XbgxBm3xltMq0G7SdSXInqQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLOjpfCCoFMRIa-MCZxT-_M",
                title: "Coding Lofi CHill",
                description: "Because debugging is less painful with chill beats :)",
                vidCount: 20,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/_ITiwPMUzho/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCdFE2e_RZb_9O5SPsNeuI9HiSctA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJ71ObeeTRRpBpgIqOpb3bq",
                title: "Pokémon Chill",
                description: "From Kanto's beginnings to the wonders of Galar and all the adventures that link them, experience the magic of Pokémon's cherished music.",
                vidCount: 21,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/VToyayJ4u2k/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IFooFDAP&rs=AOn4CLCdGv_nCNakJpACY7yO4efzfEeOzg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLb86V0Rv3t_SeWUv9T4GHL",
                title: "Minecraft Ambience",
                description: "Nostalgic ambience, peaceful gameplay, & fan-made mixes of the iconic soundtrack.",
                vidCount: 28,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/ANkxRGvl1VY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAsueBQ4bMBQPAfcpz3O02TV-briA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKCKd5DJNIwN9ptmNDoLQ8-",
                title: "Anime Chill",
                description: "Unwind to the calming melodies and sounds of anime.",
                vidCount: 21,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/TdBSoy9F9NA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6SDroyCAho5lVOce12jF1lndi5A",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLweC10nDnpdUENOuwiKckr_KinlM24sS3",
                title: "Study/Work with Cédric 📚 Chill Village",
                description: "Productive and calming lofi beats for a focused work environment in the office.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Chill Village",
                thumbnailURL: "https://i.ytimg.com/vi/guan9sTiXM0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBmfXE2t8nMURTkZR6sTPRpfOJeNg",
                channelImgSrc: "https://yt3.ggpht.com/1sjrCoAFx_Ak9g77xLRKv5na7Uz3MlvZ1KQQs-uhCtkdxFiLLTasPHH7e_NEuBO9DmPO_m9_=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@https://www.youtube.com/@Chill_Village",
                firstVidId: null
            },
            {
                id: "PLUAsF5s_xnHuViowfw54GzAVxamBYSiE2",
                title: "The Jazz Hop Café - Compilations",
                description: "Jazz meets hip-hop in a playlist that's jam-packed with chilled-out vibes!",
                vidCount: 28,
                channelId: "",
                channelTitle: "The Jazz Hop Café",
                thumbnailURL: "https://i.ytimg.com/vi/2gliGzb2_1I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvqDPQMFti6xB4MeLC2wjqf23lRQ",
                channelImgSrc: "https://yt3.ggpht.com/WqdmWxOq6FRiTtaz8u4evDCz_Dh5zN8OjlY0rGLBIHPdmx-mk8HoIA3y87RGOM9a8HJnec074pw=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheJazzHopCafe",
                firstVidId: null
            },
        ]
    },
    {
        title: "Eclectic Mix",
        playlists: [
            { 
                id: "PLpEqmyo6EfvLV0xdsE3B8QOSAx8pLLGv0",
                title: "Eclectic Grooves Sessions.",
                description: "MAJ and Friends explore rare grooves around the world on vinyl.",
                vidCount: 20,
                channelId: "",
                channelTitle: "My Analog Journal",
                thumbnailURL: "https://i.ytimg.com/vi/GyU8jToVmI8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwLumpGcDxJfq3Ut686QmOYhu49w",
                channelImgSrc: "https://yt3.googleusercontent.com/INosGb8ZVriDTJNZv_1E9Pw_TiPx0iddBfnFcSToUYDqqqINXDXLAHT0pJqJ5PuZqznx1XUUoA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@MyAnalogJournal",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvK3D9g_9K8_AX2D6E8pvCei",
                title: "NPR Tiny Desk Live Performances.",
                description: "Live, intimate artistry from the famous NPR Tiny Desk Concerts.",
                vidCount: 27,
                channelId: "",
                channelTitle: "NPR Music",
                thumbnailURL: "https://i.ytimg.com/vi/uwUt1fVLb3E/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA0RnQkpSErBTz9d3YXJrYrG3LN3g",
                channelImgSrc: "https://yt3.googleusercontent.com/INosGb8ZVriDTJNZv_1E9Pw_TiPx0iddBfnFcSToUYDqqqINXDXLAHT0pJqJ5PuZqznx1XUUoA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nprmusic",
                firstVidId: null
            },
            { 
                id: "UULP2Qw1dzXDBAZPwS7zm37g8g",
                title: "Colors Shows.",
                description: "Minimalistic shows from burgeoning musicians.",
                vidCount: 27,
                channelId: "",
                channelTitle: "COLORS",
                thumbnailURL: "https://thisisrnb.com/wp-content/uploads/2018/04/Jorja-Smith-Colors.jpg",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@COLORSxSTUDIOS",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvLVsfSgIHgh6TItYZbO1Zc1",
                title: "Japanese City Pop",
                description: "Distinct retro aesthetics of 70s / 80s Japanese City pop.",
                vidCount: 13,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.pinimg.com/564x/f7/0d/2c/f70d2cb27c271f733744445929ed7845.jpg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvKjlp0-7brbP6gXAZH0T84z",
                title: "Hip Hop Gems & Classics",
                description: "Underground tracks, classics hits, and fan-made mixes.",
                vidCount: 17,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/8nmo0PyuQQo/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYPSBlKEgwDw==&rs=AOn4CLD1sKTtWscyYN9bWjGSmhuG5yrvOg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvL0GMKgfZpFWgm8h9i1gNYN",
                title: "Jazz Gems & Classics",
                description: "An eclectic jazz mix, spanning hidden gems to classic works.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://upload.wikimedia.org/wikipedia/en/f/f8/Nala_Sinephro_-_Space_1.8.png",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvLxItVKqjJpZOS8RChsWv18",
                title: "Eclectic Mixes",
                description: "Live or in-studio. Pop, funk, jazz, lofi, or indie. A little bit of everything for diverse tastes.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/AmmFD2OIs_k/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBoz9W8WqJcHGhODrLY6598rAppaw",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvJw_sNjuNw5JC3a7irQwF8J",
                title: "Atmoshpheric & Ambient",
                description: "Tranquil soundscapes from seminal works and mixes of eclectic gems.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i1.sndcdn.com/artworks-qYI9UYzvUBEgeCaz-kTzhPg-t500x500.jpg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLpEqmyo6EfvKgNlISvuNHERoKnNNptGjk",
                title: "Latin American",
                description: "Vibrant rhythms from Latin America, from Brazilian samba to Caribbean Reggae.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/p8HoEvDh70Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC0r_IB7RXSxegJtD-2fLaayYzctQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
        ]
    },
    {
        title: "Study with Me",
        playlists: [
            {
                id: "PLr5OsF2umninLmW-yux0oONqNaQiIpJhw",
                title: "🎸Study with Calm Lofi/Quiet Jazz - Pomodoro Timer/Study/Work",
                description: "Study and work with many Calm Lofi Track and Quiet Jazz Music.",
                vidCount: 10,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/grBFMP3HDZA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAGAboCwXsa6WC-fZvCc9atdetYA",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLmWo-cY6xKJbFIhZZZ-dm599XwucdH6gW",
                title: "Real Time Study With Me",
                description: "Enjoy these real time study with me videos to boost your productivity with me :)",
                vidCount: 14,
                channelId: "",
                channelTitle: "Kharma Medic",
                thumbnailURL: "https://i.ytimg.com/vi/fJP7c8xt1n4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADBddEjw38mdfAOgxIzPZjbvLV_w",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqNTfqDJWJCGaH1_SDvNveiG2xDmlsif8XWM3UaBCg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@KharmaMedic",
                firstVidId: null
            },
            {
                id: "PLr5OsF2umninjc42Ia_bzEjKKi9QgHaWU",
                title: "🎧Study with Music - Pomodoro Timer/Study/Work",
                description: "Study with productivity guru \"Abao in Tokyo\" while listenting to some chill tunes.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/sca4VG9b0NY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCzrqQ5S5zh5StvkhR1jB1Pvl4Hgw",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLr5OsF2umnimZ5DUoXnMaKmqa8CwUTb3z",
                title: "Ambient version - Pomodoro Timer/Study/Work",
                description: "Study and work with Sound of Rain, firewood, and environment.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/UwQp8vOlD14/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCXtNcd2qtxhU09b3J3nbnyAG13PA",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLdoPDZp9cQnVTyZLzSG91bqEylKwfkpbj",
                title: "Complete Study With Me Playlist",
                description: "This playlist contains all my study with me videos for your convenience!",
                vidCount: 0,
                channelId: "",
                channelTitle: "The Strive Studies",
                thumbnailURL: "https://i.ytimg.com/vi/pRKGH8soIbk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3BzTT05ZeQo3poVT9F9TIvWriYA",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqNS1mtOUxWDpE8rE1Jb2p87ZIErrTCHs56aERkk=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheStriveStudies",
                firstVidId: null
            },
            {
                id: "PLnBcyEFLuLUtrJZbnFCv6_IO7AfZcD7E8",
                title: "StudyMD - Study with Me",
                description: "Join productivity master StufyMD for some study sessions to help you stay motivated!",
                vidCount: 23,
                channelId: "",
                channelTitle: "StudyMD",
                thumbnailURL: "https://i.ytimg.com/vi/08DochENii8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLClxqpVojlNsbhAHIKVj_1_XO2klA",
                channelImgSrc: "https://yt3.googleusercontent.com/L0W93fDHgz9L_GGkmZvouFGNbbvHARFVhPsDVjK5NP-GqdUPPTDGwFQkUlDzh-WaOJmsx0DN3w=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@StudyMD",
                firstVidId: null
            },
        ]
    },
    {
        title: "Ambience",
        playlists: [
            {
                id: "PLkmb1BBi8y93GnJ_yClUZei92tCg49Do4",
                title: "City Ambience",
                description: "Ambient sounds from cities around the world.",
                vidCount: 49,
                channelId: "",
                channelTitle: "Nomadic Ambience",
                thumbnailURL: "https://i.ytimg.com/vi/F8MN0o6RS9o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCF3DJWwdAlGhhYB0E1KoB17ooDLA",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                firstVidId: null

            },
            {
                id: "PLpEqmyo6EfvKqGFfjS3r8OXZtjKexkikR",
                title: "Nature Ambience",
                description: "The serenity of nature in a soothing, 4k ambient experience.",
                vidCount: 13,
                channelId: "",
                channelTitle: "Nature Soundscapes",
                thumbnailURL: "https://i.ytimg.com/vi/qRTVg8HHzUo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCgM2LaUhy3mSWfKCzJ8ysmYiwv6Q",
                channelImgSrc: "https://yt3.googleusercontent.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Nature_Soundscapes",
                firstVidId: null

            },
            {
                id: "PLkmb1BBi8y93GnJ_yClUZei92tCg49Do4",
                title: "Rain Ambience",
                description: "Collection of relaxing rain ambience sounds videos from around the world.",
                vidCount: 46,
                channelId: "",
                channelTitle: "Nomadic Ambience",
                thumbnailURL: "https://i.ytimg.com/vi/V_vj7BMawAI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC8qxKnT8LysNMSeYhJ2wwO0-nYIg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKUkEnRlAdbVvpMBACpu7Lu",
                title: "Natural Soundscapes Mix",
                description: "Nature's music, from rainy forests and snowy hills to cozy fires and distant thunder. From within nature or in civilization.",
                vidCount: 35,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/SnUBb-FAlCY/hqdefault.jpg?sqp=-oaymwExCNACELwBSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYMCBlKEkwDw==&rs=AOn4CLBiDPsaBueqw3dcsR83moVY1C38MQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLkmb1BBi8y93qIwNcnuo3e9oyLxc8PVGB",
                title: "Nature Ambience Sounds",
                description: "Collection of relaxing nature ambience sounds videos from around the world.",
                vidCount: 35,
                channelId: "",
                channelTitle: "Nomadic Ambience",
                thumbnailURL: "https://i.ytimg.com/vi/3raVUTPAd-w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZQfehA5iuyiPzh6SdBJsk9dCtvw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                firstVidId: null
            },
            {
                id: "PLvTaXqHhgyZ7XuuhDZtQeTif54Warh0Db",
                title: "Rain Ambience",
                description: "Relaxing rain sounds for focusing, meditating, sleeping, and calming anxiety.",
                vidCount: 35,
                channelId: "",
                channelTitle: "Calmed By Nature",
                thumbnailURL: "https://i.ytimg.com/vi/c0_ejQQcrwI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIMjFPok4MQ53trfOj9U5NdIAs5g",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM5X1aJOEuFHVtUqrKuUYJJ9TGZFGBe4U0KL6hg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@CalmedByNature",
                firstVidId: null
            },
            {
                id: "PLYSqJ3BBUHqhGnPS7yQk0ss3LM58TiYSP",
                title: "Lord of the Rings Music & Ambience",
                description: "Step into Middle-Earth and enjoy the sights and sounds of your favorite iconic locations.",
                vidCount: 35,
                channelId: "",
                channelTitle: "Ambient Worlds",
                thumbnailURL: "https://i.ytimg.com/vi/uBmbI8dzc-M/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCHJeuVTDQpFrGmbdbe5mWnOyoZ5Q",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                firstVidId: null
            },
            {
                id: "PLYSqJ3BBUHqho9Af8rZQCfJwiYtNGdzAA",
                title: "Harry Potter Music and Ambience",
                description: "Escape into the the Wizarding World of Harry Potter!",
                vidCount: 40,
                channelId: "",
                channelTitle: "Ambient Worlds",
                thumbnailURL: "https://i.ytimg.com/vi/xLwm252AqJ8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDzi3ykbRPFH_HRqTvZ3TOyI69lRw",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                firstVidId: null
            },
            {
                id: "PLYSqJ3BBUHqgjle62yugHm494ENDefd57",
                title: "Star Wars Music & Ambience",
                description: "Atmospheric soundscapes from a distant galaxy, far, far away.",
                vidCount: 9,
                channelId: "",
                channelTitle: "Ambient Worlds",
                thumbnailURL: "https://i.ytimg.com/vi/83n4pLUhTmk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBd_45I6xQG17TaVSPJTnCZdWHDJQ",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                firstVidId: null
            },
        ]
    },
    {
        title: "Archictecture",
        playlists: [
            {
                id: "PLpi4YdMCC439sN_5vIza6IfQm0qc-IqPO",
                title: "Open Door: Inside Celebrity Homes",
                description: "Visit the extravagant homes of your favorite athletes, artists, musicians, & actors.",
                vidCount: 150,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/D-qQneOnJl0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADKxJSiTHX6Vt_69xRORV_DbvHVg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            },
            {
                id: "PLpi4YdMCC439LJOnJyIgLR98zCazUGNwq",
                title: "Walking Tour",
                description: "Explore world famous cultural sites from Tokyo to the Côte d'Azure while staying cozy in your PJs!",
                vidCount: 12,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/EuNguMnSKnA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLChHTKsXAKbartzBAC7F3XakBbNsQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            },
            {
                id: "UULPgxg48_pay4R67s-7WOgWFA",
                title: "Local Project House Tours",
                description: "Experience the ingenuity of Austrialia's best architects.",
                vidCount: 184,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/dZEgImpC1GI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAVAg1B0o4EhhoStWRdFUhL6jodCg",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PLirM94SQW73BAPwA09CDbGd6RRMK4SJpp",
                title: "An Architect's Own Home",
                description: "Step inside architects' abodes for design revelations and personal inspirations.",
                vidCount: 30,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/J4_rLK7F4fw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7rMhQ_puQrsh8sB2Cl_iiFsoA_w",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PLirM94SQW73AXi3KRoq3bsGphry4Znoe_",
                title: "Tiny Homes and Cabins",
                description: "Explore cozy living with stunning tiny homes and cabins.",
                vidCount: 12,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/9Eu0nHapqf0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCks4Pc293qBBzIKMf8ejy6Q76S0g",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PL1WZky7MVeY_6H2ieeVKitXGd3npyPo-g",
                title: "NEVER TOO SMALL Official Playlist",
                description: "Explore space-saving marvels in the innovative designs of compact living environments.",
                vidCount: 150,
                channelId: "",
                channelTitle: "NEVER TOO SMALL",
                thumbnailURL: "https://i.ytimg.com/vi/bA6C7QvTqZQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKtmnlvwJBpZbWf1_XBuDYcmJG2w",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPu1g1VZ5_9vzfGYd9O6p_c0EK3N3Z8TrpRux12Hw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nevertoosmall",
                firstVidId: null
            },
            {
                id: "UULPoc2ZM2cYas4DijNdaEJXUA",
                title: "Architectural Design",
                description: "A detailed insight into the design process of a skilled architect.",
                vidCount: 40,
                channelId: "",
                channelTitle: "30X40 Design Workshop",
                thumbnailURL: "https://i.ytimg.com/vi/ly8orBNiNQM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBMl-IO2s2XziXqmOneR8iVbNeJGg",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@30by40",
                firstVidId: null
            },
            {
                id: "PL999ZDYL8QbTqnT8PZshZzJa7tat-Vdcj",
                title: "Tiny House Tours",
                description: "Experience unique tiny homes worldwide, celebrating sustainable living and creative design.",
                vidCount: 292,
                channelId: "",
                channelTitle: "Living Big In A Tiny House",
                thumbnailURL: "https://i.ytimg.com/vi/wAsXkkLumrk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCE1YQe2sTpdeZbkAtTMnWtbaSLbw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM49fR69HbYoFhsWkmCsi7SwgDIfrZA3ayVzXM4cw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@livingbig",
                firstVidId: null
            },
            {
                id: "PLpi4YdMCC439_CyF_AcdIhHNZXGmejGtw",
                title: "Architects do Makeovers",
                description: "A close look at the design processes of accomplished architects.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/f2HVUN0d4Jo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPsyOwZPkX6jMFfj-ku2f9DAK9ow",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            },
        ]
    },
    {
        title: "Arts",
        playlists: [
            {
                id: "PLpEqmyo6EfvLFKVCc1RzCoUGfGMqJV_Kg",
                title: "Art of Craft",
                description: "Find inspiration from artist profiles & demonstrations of their craft.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Different Authors",
                thumbnailURL: "https://i.ytimg.com/vi/vcoRoP3Abt8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR8SjK-LpyqF8EP5mYNTOpUumqWg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLBfTZweZnGN_QTosoWO_2i",
                title: "Sketchbook Tours",
                description: "Step inside the personal sketchbooks of some extraordinary artists.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Multiple Artists",
                thumbnailURL: "https://i.ytimg.com/vi/OmLkBQmZQM8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAm1MJt-sbBgIwMGQIpbQlzVWBrQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "UULPePDFpCr78_qmVtpoB1Axaw",
                title: "Great Art Explained",
                description: "Deciphering some of history's greatest artworks, from \"The Starry Night\" to \"Nighthawks.\"",
                vidCount: 32,
                channelId: "",
                channelTitle: "Great Art Explained",
                thumbnailURL: "https://i.ytimg.com/vi/IBcB_dYtGUg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLsrhuZlz8kzcOwffTFXF6pchw4g",
                channelImgSrc: "https://yt3.ggpht.com/SVoD_4bbVOt1Nc3ncoDbMq7s-LU87TWovuFlUw3O0wQAKik0lwMwccnCWcp65cHSnZ4SQbuDPCc=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BaumgartnerRestoration",
                firstVidId: null
            },
            {
                id: "PLOBH6dux3B0gLfU6SK7IdWeCZMa49H___",
                title: "Art Book Reviews",
                description: "Insightful critiques and explorations of the artworks from amazing films & video games.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Adam Duff LUCIDPIXUL",
                thumbnailURL: "https://i.ytimg.com/vi/hXkbS8A-qo0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdpEaRG44I1gqG4xAWmf1A0FKLDg",
                channelImgSrc: "https://yt3.googleusercontent.com/stXTo4OSGjHAwwQ7zwRH8xHF24_jBFmfnyJEn7a9YUBeS_k9xTwdka8J15mL5MFfQ85naI0O6A=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AdamDuffArt",
                firstVidId: null

            },
            {
                id: "PLFB0oFTSWSYb1mpL9YCFAT1YmSl3G--Ew",
                title: "3D Render Montages",
                description: "Get inspired by the works of hundreds of digital artists from pwnisher's 3D render challenges.",
                vidCount: 10,
                channelId: "",
                channelTitle: "pwnisher",
                thumbnailURL: "https://i.ytimg.com/vi/EdCvwmebWN0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArWq2ck_Aub2tg0mWSR1yc4E4rhQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ER3I3TTJPZ6s7F0ARY1a88touU80pbINHVK8iYD45HC-TgEmcpcQJqVAVNxC4jxjcIGTQ1fe=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@pwnisher",
                firstVidId: null
            },
            {
                id: "PL5JqSuIvtmAMFmxJcr-v-9iTl4RY6nN5s",
                title: "Art History",
                description: "Learn about the centuries of art history from the Renaissance to 19th Century Romanticism.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Perspective",
                thumbnailURL: "https://i.ytimg.com/vi/XA_CqvjQWu8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAv-wC4b_dVCFJhYfDakd-7eEdkmA",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@PerspectiveArts",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvIlazR90JTrBOEMi44x-5Ct",
                title: "LOTR Appendices",
                description: "LOTR’s creative brilliance in filmmaking, fashion, music & more is displayed in this amazing BTS look at the making of some of the best films ever made.",
                vidCount: 9,
                channelId: "",
                channelTitle: "Everything In Middle Earth",
                thumbnailURL: "https://i.ytimg.com/vi/MY8i0E7TdWs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAmAvI2HUoic0Y_fSA1JX90HI9QZQ",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@EverythingInMiddleEarth",
                firstVidId: null

            },
            {
                id: "PLpEqmyo6EfvIUMb4z97ohT4GGyy14FDsa",
                title: "Great Big Story - Art Stories",
                description: "Explore the stories of artist around the world for boundless inspiration.",
                vidCount: 27,
                channelId: "",
                channelTitle: "Great Big Story",
                thumbnailURL: "https://i.ytimg.com/vi/xMgz61YjoLU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjRWtbDgt0GV4CDjRjVgW5NsynEQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ek2CK7M2HU9SCi7SkN10_1BfP7HpEjXA7lieUdPgamKJYhyJbLezmsj7rF3t6KtTOZl0Zrq1IQ=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@GreatBigStory",
                firstVidId: null
            },
            {
                id: "UULPNNOvB507MRfny7Jcv8MmOw",
                title: "Sam Does Art",
                description: "Reactions and helpful tips from the one the internet's most popular digital artists.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Sam Does Arts",
                thumbnailURL: "https://i.ytimg.com/vi/wZxc71tUz8s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVO8isTqAgkELDBZAsTJVV_cZiug",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM5ZbMDBn9PJevUnYNm-7cNzr44NPGOOXgI8Hct=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@samdoesarts",
                firstVidId: null

            },
        ]
    },
    {
        title: "History",
        playlists: [
            {
                id: "PLpEqmyo6EfvJFLREnGokXuPh7gOHi1Tug",
                title: "Hellenic Cultures",
                description: "An odyssey through Greek cultures, from the Spartans to the Macedonians.",
                vidCount: 11,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/6eMKOoZdvJo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTQAOBxMLn7sozyz8JDgrCaPslzg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJPF7dX3T5r6PN0ocjO74l6",
                title: "Asiatic and Middle Eastern",
                description: "History stretching from the Persians and the Abassids to the Chinese dynasties and Feudal Japan.",
                vidCount: 19,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/XdOxBCpk39c/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBUQMtelhX0WsEBDOXY-vRDqrJ3Yw",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKTRi2DsmY76zIDxNw81uGf",
                title: "Rome",
                description: "Travel back to the time when togas and imperical conquest were all the rage.",
                vidCount: 8,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/CU2AOz8sav4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl9frJrxtNp4plAzkcENOoxwSN0Q",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLUOc2qodFHp-mOphKW9RzQLsFTt-IV9RY",
                title: "Napoleonic Wars",
                description: "Delve into campaigns that bore an empire spear-headed by one of history's greatest military figures.",
                vidCount: 28,
                channelId: "",
                channelTitle: "Epic History TV",
                thumbnailURL: "https://i.ytimg.com/vi/nDZGL1xsqzs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVtD39mdAG0acFwDBvd2fyWsl4nQ",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKQWp9RPpTQVppb7Ix_a_Lg",
                title: "Ancient Egypt",
                description: "Unearth the mysteries and wonders of Ancient Egypt's rich history.",
                vidCount: 12,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/ZrJe2Ab2t0Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9leLyG_Eh9mJUdoUVUzevBjAk8g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLq0ER3EMJsCFXxap9t3JNbq1dX-49z16o",
                title: "Legends And Mysteries",
                description: "Delve into the beguiling mysteries and myths of the ancient world.",
                vidCount: 11,
                channelId: "",
                channelTitle: "Odyssey - Ancient History Documentaries",
                thumbnailURL: "https://i.ytimg.com/vi/ysnzl5fdtMI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCCUlrUFU16ddFC8hIrXWtG5lMyaw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@odyssey",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJkYaea8zUmutNpt3jiZXp5",
                title: "Prehistory",
                description: "Explore the roots human ancestry and the animals they lived with from the Stone Age to Bronze Age.",
                vidCount: 8,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/vJybfmbrOCE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBH-W80DpEAvzmwOE6BVlThyFB3Zg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLq0ER3EMJsCEbrCW0lE3COXpQrw3791qH",
                title: "Timeline's Ancient Civilisations",
                description: "Step back in time to the glory days of Ancient Rome.",
                vidCount: 19,
                channelId: "",
                channelTitle: "Timeline - World History Documentaries",
                thumbnailURL: "https://i.ytimg.com/vi/RCI28U2TvVs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZPnHpRxmjEtoYH2f1QJfKT2EoVQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPjQK0xKlyZpbWUMzcE5BcJHvArxeKNCki2ijo1Pg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TimelineChannel",
                firstVidId: null
            },
            {
                id: "PLUOc2qodFHp8mvnBE_Ya6Bj0HYnRo4XiY",
                title: "Epic History TV",
                description: "Dramatic, fast-moving, fact-packed history videos to help you make sense of epic events that have shaped the modern world.",
                vidCount: 93,
                channelId: "",
                channelTitle: "Epic History TV",
                thumbnailURL: "https://i.ytimg.com/vi/K7lb6KWBanI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAg7bIfY5tljmHe_WHysOttvs__MQ",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                firstVidId: null
            },
            {
                id: "PLOjUdznmpOjjsJxgmAzwjdsoDomZjGYmc",
                title: "Medieval Battles",
                description: "Witness the epic clashes between armies of historic battles from antiquity.",
                vidCount: 28,
                channelId: "",
                channelTitle: "Baz Battles",
                thumbnailURL: "https://i.ytimg.com/vi/BV5Z_CHbkAw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCC12FXPNGVlK33rDIU0vniXLX0fg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                firstVidId: null
            },
            {
                id: "PLOjUdznmpOjiJQD_rOpw4iX8Vj-AoxGUe",
                title: "Game of Thrones",
                description: "Not exactly history but GOT has the grounded realism to feel like so.",
                vidCount: 5,
                channelId: "",
                channelTitle: "Baz Battles",
                thumbnailURL: "https://i.ytimg.com/vi/k1zsvHusfPQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBswM110Dk6U6XWHlztR2bQt6B70w",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                firstVidId: null
            },
        ]
    },
    {
        title: "Culture",
        playlists: [
            {
                id: "PLpEqmyo6EfvKJaI7Rl1Y0zvxkPVjqfPwX",
                title: "Kraig Adams Hiking Videos",
                description: "Experience some of the world's pretties natural wonders with Kraid Adams' theraputic hiking videos.",
                vidCount: 22,
                channelId: "",
                channelTitle: "Kraig Adams",
                thumbnailURL: "https://i.ytimg.com/vi/WKcnvPDgifA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQhlIq7mkeUHGT6-QFER1u4-qcUw",
                channelImgSrc: "https://yt3.googleusercontent.com/Q5rf5ItB1wumirWCX0cVO7d31Hi4N1B5vIWthJ7Bx8_1KyIAiFXFkGS0CLqBpowSicJMdI32B40=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@kraigadams",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJseQSBPD78gFiwgI6t9p1K",
                title: "Nature Docs",
                description: "Find serenity in Earth's natural treasures, from the heart of the Amazon Rain Forest to the vast stretches of the African Savannah.",
                vidCount: 11,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/JkaxUblCGz0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCHAgPno9ZlrIdpdJ1IjPcT0CsrcQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKXJDoVj2k3Xo6wcZM7qgXt",
                title: "THR Roundtables",
                description: "Candid conversations with titans of the film industry.",
                vidCount: 20,
                channelId: "",
                channelTitle: "The Hollywood Reporter",
                thumbnailURL: "https://i.ytimg.com/vi/hJH2EyvvEBA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAjkFRfVJjH-DS2rBdGRA1TrU7UcQ",
                channelImgSrc: "https://yt3.googleusercontent.com/7FPGaZ3f81d6IXj-eZwD5_f8UhKNFTMg6jvesjs42nnEwTKrFGnIBGqxbP0QZs2MyAKF2zQHmFA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@hollywoodreporter",
                firstVidId: null
            },
            {
                id: "PLW1Mwtj8qAjmvVnVEbBhbcBOAFWlj8mOs",
                title: "Regional Eats",
                description: "We travel to a food's area of origin to see how it's made, find out its history.",
                vidCount: 82,
                channelId: "",
                channelTitle: "Insider Food",
                thumbnailURL: "https://i.ytimg.com/vi/ZyZh_FIhGlU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwFZ0JRuVsIJ-rl4mYJFNUY-HI8g",
                channelImgSrc: "https://yt3.googleusercontent.com/my5fZEjea_-N5p8mhqrdNIxghb-KjP9AcH4lQlYzNrRlwzjx3Gbay0JlOCZqJOcp_sTjF3rmBV8=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@InsiderFood",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLXwNAneyYbEgxM4o5GinX6",
                title: "Walking Tours",
                description: "Explore world famous cultural sites from Tokyo to the Côte d'Azure while staying cozy in your PJs!.",
                vidCount: 8,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/F8MN0o6RS9o/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDJkmw9p12FfxuO2OnDi-PTJ1FwyA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLnPDn1Lb79JFjhC17KjxiFU41SKivZfrW",
                title: "Street Food Icons",
                description: "Discover the legendary founders of famous street-food eateries all over the world.",
                vidCount: 82,
                channelId: "",
                channelTitle: "Munchies",
                thumbnailURL: "https://i.ytimg.com/vi/Fpny0WP8sYw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByNtcd0gC-usJeeaAvmRfi_oB7mQ",
                channelImgSrc: "https://yt3.googleusercontent.com/JU6HzojvmJwDKybljkQc83LESYZG7NmdPgPo2xXoeHUcUmR98tHjIUhIekgMFGaRyEDgzuv-AA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Munchies",
                firstVidId: null
            },
            {
                id: "PLcpuu5BzmasC7cI-B713EY3xdpWrLhDdH",
                title: "Japan Day in the Life Series by Paolo from TOKYO",
                description: "Paolo's 'Day-in-the-life' series provides an unmatched, intimate peek into modern day Japanese life.",
                vidCount: 39,
                channelId: "",
                channelTitle: "Paolo from TOKYO",
                thumbnailURL: "https://i.ytimg.com/vi/B5pKw6flFZE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAghIXJ5n9TxupLK1lpkmDfcKvLCw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@PaolofromTOKYO",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJEd06jNTuUSr9Z3ITXhjbT",
                title: "Vogue Street Style",
                description: "From the streets of Conpenhagen and Paris to Tokyo and Milan, get inspired by fits of fashion enthusiasts around the world.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Vogue",
                thumbnailURL: "https://i.ytimg.com/vi/zPys5ZYL-ng/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByf0Jsm8dNJ21M7nX2IkaPPVIMTw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@Vogue",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLNXuV81RFTboiERUsr73Yf",
                title: "Best Ever Food Review Show",
                description: "Sonny’s culinary journeys around the world offers some of the most entertaining and enriching food content available.",
                vidCount: 82,
                channelId: "",
                channelTitle: "Best Ever Food Review Show",
                thumbnailURL: "https://i.ytimg.com/vi/a5yP1yqGEMo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBYc1gfrW0rEMDlyfIldjr9TDL3OQ",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@BestEverFoodReviewShow",
                firstVidId: null
            },
            {
                id: "PL1OajwstW05Hlp6Le5OgA1yZ9QEyxfBnJ",
                title: "Rick Stevens Travel Guide",
                description: "Rich Stevens famous travel guide series explores most beautiful sites in Europe.",
                vidCount: 123,
                channelId: "",
                channelTitle: "Rick Steves' Europe",
                thumbnailURL: "https://i.ytimg.com/vi/WP316ABiTt0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDfOJ-d49kBNplh2Bqr1ggtsHSmIw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMx_-Mkmuil3vVoHCg6KgDpC-5EUzGr616CwhTg7g=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@ricksteves",
                firstVidId: null
            },
        ]
    },
    {
        title: "News & Politics",
        playlists: [
            {
                id: "PLMFGVXWuJ1C7Bcu6apMqmP3B0yL0BeJRe",
                title: "Great Big Picture",
                description: "Delivering unique and enriching stories about people from around the global that often overlooked by mainstream media.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Great Big Story",
                thumbnailURL: "https://i.ytimg.com/vi/ykYfP7iqOto/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCmWZk7rMfkihhm7npvAE7Au3r1ew",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@GreatBigStory",
                firstVidId: null
            },
            {
                id: "PLw613M86o5o7q1cjb26MfCgdxJtshvRZ-",
                title: "Vice News",
                description: "Stay informed and up-to-date with news that capture the people at the heart of stories, and focus on the ideas, issues, and context that moss outlets miss.",
                vidCount:  1000,
                channelId: "",
                channelTitle: "Vice News",
                thumbnailURL: "https://i.ytimg.com/vi/d-Dkm_-1uaY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCuwVd_2l4sNvkgnxRmtp2eu7ps6g",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@VICENews",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKcNODQCgDNAO5o09yXvJD-",
                title: "Best of Vice News",
                description: "Our favorite pieces of journalism from Vice News.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Vice News",
                thumbnailURL: "https://i.ytimg.com/vi/iIFi_Rgm-T8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAWPRdAGdU3LNv__jDWjXvRNYEASw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@VICENews",
                firstVidId: null
            },
            {
                id: "PLzGHKb8i9vTztD1EkX_S0V0Agv8IUDP-C",
                title: "Al Jazeera Breaking News",
                description: "Real-time updates on the latest headlines.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Al Jazeera English",
                thumbnailURL: "https://i.ytimg.com/vi/KBsSuW2c1pQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqnIdXyHOZtF1mj0xrV0c9jhT_Sw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@aljazeeraenglish",
                firstVidId: null
            },
        ]
    }
]

export default ytRecsPlaylists