const ytRecsPlaylists = [
    {
        title: "Lofi / Jazz",
        playlists: [
            {
                title: "Lofi Girl - Compilations",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/zFhfksjf_mY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQgYKl48s3nIAYnxSDbiy65PL42g",
                playlistDescription: "Curated compilation of Lofi Girl's beloved and soothing videos for ultimate relaxation and chill vibes.",
                playlistId: "PL6NdkXsPL07KN01gH2vucrHCEyyNmVEx4",
                channelTitle: "Lofi Girl",
                channelImgSrc: "https://yt3.googleusercontent.com/gY8H7K-3Eg3olVftRBiqqFe-N5d9Rx90jAsrfQuxDa4m32Wm-kWK6AQJhwchvYLf-H4EjGhCSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@LofiGirl",
                vidCount: 16,
            },
            {
                title: "Lofi Girl - Albums",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/qdU7RgF8exI/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB1AaAAuADigIMCAAQARhNIEMocjAP&rs=AOn4CLA-FNZWIprKMrDIxJij0A4Djk0dIA",
                playlistDescription: "Longer compilation of Lofi Girl's chill videos.",
                playlistId: "PL6NdkXsPL07IOu1AZ2Y2lGNYfjDStyT6O",
                channelTitle: "Lofi Girl",
                channelImgSrc: "https://yt3.googleusercontent.com/gY8H7K-3Eg3olVftRBiqqFe-N5d9Rx90jAsrfQuxDa4m32Wm-kWK6AQJhwchvYLf-H4EjGhCSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@LofiGirl",
                vidCount: 200,
            },
            {
                title: "The Jazz Hop Café - Mixes",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/TYCBicKyVhs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAxH2OcNzH6KHMd839rWzwG0r8koA",
                playlistDescription: "Explore a captivating collection of lo-fi and jazz playlists, perfect for cozy moments and relaxing vibes.",
                playlistId: "PLUAsF5s_xnHtw0CAoHTYDESe9o2BKCRIN",
                channelTitle: "The Jazz Hop Café",
                channelImgSrc: "https://yt3.ggpht.com/WqdmWxOq6FRiTtaz8u4evDCz_Dh5zN8OjlY0rGLBIHPdmx-mk8HoIA3y87RGOM9a8HJnec074pw=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheJazzHopCafe",
                vidCount: 108,
            },
            {
                title: "The Jazz Hop Café - Compilations",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/2gliGzb2_1I/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAvqDPQMFti6xB4MeLC2wjqf23lRQ",
                playlistDescription: "Jazz meets hip-hop in a playlist that's jam-packed with chilled-out vibes!",
                playlistId: "PLUAsF5s_xnHuViowfw54GzAVxamBYSiE2",
                channelTitle: "The Jazz Hop Café",
                channelImgSrc: "https://yt3.ggpht.com/WqdmWxOq6FRiTtaz8u4evDCz_Dh5zN8OjlY0rGLBIHPdmx-mk8HoIA3y87RGOM9a8HJnec074pw=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheJazzHopCafe",
                vidCount: 28,
            },
            {
                title: "Study/Work with Cédric 📚 Chill Village",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/guan9sTiXM0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBmfXE2t8nMURTkZR6sTPRpfOJeNg",
                playlistDescription: "Productive and calming lofi beats for a focused work environment in the office.",
                playlistId: "PLweC10nDnpdUENOuwiKckr_KinlM24sS3",
                channelTitle: "Chill Village",
                channelImgSrc: "https://yt3.ggpht.com/1sjrCoAFx_Ak9g77xLRKv5na7Uz3MlvZ1KQQs-uhCtkdxFiLLTasPHH7e_NEuBO9DmPO_m9_=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@https://www.youtube.com/@Chill_Village",
                vidCount: 20,
            },
            {
                title: "Chill Village Official Playlist",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/1XINzGSZT4o/hqdefault_live.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDa7EEjP-eLVXsysg6RKLHKYlHr_g",
                playlistDescription: "Your personal escape from chaos. Embrace the chill vibes and zen out.",
                playlistId: "PLweC10nDnpdUripJHl6O9SZZ73GVcnW8W",
                channelTitle: "Chill Village",
                channelImgSrc: "https://yt3.ggpht.com/1sjrCoAFx_Ak9g77xLRKv5na7Uz3MlvZ1KQQs-uhCtkdxFiLLTasPHH7e_NEuBO9DmPO_m9_=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@https://www.youtube.com/@Chill_Village",
                vidCount: 119,
            },
            {
                title: "Poké & Chill ~ Lofi Hiphop by Mikel",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/2DVpys50LVE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDBFgnMvfnYFB57ytj9BzawffqLUg",
                playlistDescription: "Unleash nostalgia with Pokémon-inspired lo-fi beats, capturing the essence of your favorite adventures",
                playlistId: "PLBsm_SagFMme7PusfP7l30tCcAxQe9lvX",
                channelTitle: "Game Chops",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPF5XGLboNObSrHAsbDqmAcEPZREUpk5Zy-PVokhA=s88-c-k-c0x00ffffff-no-rj-mo",
                channelURL: "https://www.youtube.com/channel/UCDVKYPXwdYUQfgA05CkyFSg",
                vidCount: 21,
            },
            {
                title: "Pokemon Relaxing Music Compilations",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/-BKfhq_TtcE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCcVbQdKtqVXb2jmZQgBJhXcMMEwA",
                playlistDescription: "Unwind and recharge with soothing Pokémon melodies in this relaxing music compilation.",
                playlistId: "PL8sXnvCokOzmT_c7jahpCTuVcCn9bVL-m",
                channelTitle: "braix",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqOPOOEKuhj-DqK9mXw7_7qVTbf0utnuLkyG8iGjKg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@buraikusu",
                vidCount: 21,
            },
            {
                title: "Chillhop Radio - jazzy & lofi hip hop beats 🐾",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/jU5uheLFYi0/hqdefault_live.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA5-5igzibwUzmNJZrUkT2bohTO2Q",
                playlistDescription: "Laid-back jazzy & lofi hip hop beats for a cozy and relaxed vibe",
                playlistId: "PL21ubKuUJp_dG6Y2yqFW79KAKBdZXysPX",
                channelTitle: "RELAXATION (LoFi & CHILL)",
                channelImgSrc: "https://yt3.ggpht.com/nR7cakMqnjBUMEZF1OZiUYE_zpdkvfqm3G72Eu67p8y-9Ue14nlSDNAqqcQhdOWIHZfXUMu4Rg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@relaxationlofichill4087",
                vidCount: 200,
            },
            {
                title: "Studio Ghibli Music",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/3jWRrafhO7M/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCfcVlLc3Bm6aqaCf2ybO_IRa53cQ",
                playlistDescription: "Captivating melodies that transport you into the enchanting world of Studio Ghibli.",
                playlistId: "PLYyJCobshLZlTxiQvR12noxc38n0zXv0G",
                channelTitle: "Cafe Music BGM channel",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqNdDW3hiE1udWI4eI086Qa3qu41ltejJ3EGvXovzQ=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/channel/UCJhjE7wbdYAae1G25m0tHAA",
                vidCount: 14,
            },
            {
                title: "Jazz music for relax, study and work",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/rpwxhOwiMzI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAQ6RTU_e8rDKAi-rDipY_hGrow-A",
                playlistDescription: "Smooth tunes to relax, focus, and enhance productivity during study and work sessions.",
                playlistId: "PLxmNTgb6VxBz3v4cGYtKydbgtABn68pjo",
                channelTitle: "Coffee Relaxing Jazz",
                channelImgSrc: "https://yt3.googleusercontent.com/4WEURbGBEs0-N63_SNeB_NdAltYDNVccI-85TYp0bRqkPhG3ye1PvSIWEGGcJ0W6hVHTvfzIcw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@coffeerelaxingjazz",
                vidCount: 3,
            }
        ]
    },
    {
        title: "Study with Me",
        playlists: [
            {
                title: "Real Time Study With Me",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/fJP7c8xt1n4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADBddEjw38mdfAOgxIzPZjbvLV_w",
                playlistDescription: "Enjoy these real time study with me videos to boost your productivity with me :)",
                playlistId: "PLmWo-cY6xKJbFIhZZZ-dm599XwucdH6gW",
                channelTitle: "Kharma Medic",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqNTfqDJWJCGaH1_SDvNveiG2xDmlsif8XWM3UaBCg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@KharmaMedic",
                vidCount: 14,
            },
            {
                title: "Complete Study With Me Playlist",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/6nn4xG7nbP4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDhmrJciF_He7wXTY9G8uMdxutweQ",
                playlistDescription: "This playlist contains all my study with me videos for your convenience!",
                playlistId: "PLdoPDZp9cQnVTyZLzSG91bqEylKwfkpbj",
                channelTitle: "TheStrive Studies",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqNS1mtOUxWDpE8rE1Jb2p87ZIErrTCHs56aERkk=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheStriveStudies",
                vidCount: 0,
            },
            {
                title: "StudyMD - Study with Me",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/08DochENii8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLClxqpVojlNsbhAHIKVj_1_XO2klA",
                playlistDescription: "Join productivity master StufyMD for some study sessions to help you stay motivated!",
                playlistId: "PLnBcyEFLuLUtrJZbnFCv6_IO7AfZcD7E8",
                channelTitle: "StudyMD",
                channelImgSrc: "https://yt3.googleusercontent.com/L0W93fDHgz9L_GGkmZvouFGNbbvHARFVhPsDVjK5NP-GqdUPPTDGwFQkUlDzh-WaOJmsx0DN3w=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@StudyMD",
                vidCount: 23,
            },
            {
                title: "🎸Study with Calm Lofi/Quiet Jazz - Pomodoro Timer/Study/Work",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/grBFMP3HDZA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAGAboCwXsa6WC-fZvCc9atdetYA",
                playlistDescription: "Study and work with many Calm Lofi Track and Quiet Jazz Music.",
                playlistId: "PLr5OsF2umninLmW-yux0oONqNaQiIpJhw",
                channelTitle: "Abao in Tokyo",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                vidCount: 10,
            },
            {
                title: "🎧Study with Music - Pomodoro Timer/Study/Work",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/sca4VG9b0NY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCzrqQ5S5zh5StvkhR1jB1Pvl4Hgw",
                playlistDescription: "Study with productivity guru \"Abao in Tokyo\" while listenting to some chill tunes.",
                playlistId: "PLr5OsF2umninjc42Ia_bzEjKKi9QgHaWU",
                channelTitle: "Abao in Tokyo",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                vidCount: 20,
            },
            {
                title: "Ambient version - Pomodoro Timer/Study/Work",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/UwQp8vOlD14/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCXtNcd2qtxhU09b3J3nbnyAG13PA",
                playlistDescription: "Study and work with Sound of Rain, firewood, and environment.",
                playlistId: "PLr5OsF2umnimZ5DUoXnMaKmqa8CwUTb3z",
                channelTitle: "Abao in Tokyo",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                vidCount: 20,
            }
        ]
    },
    {
        title: "Ambience",
        playlists: [
            {
                title: "City Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/F8MN0o6RS9o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCF3DJWwdAlGhhYB0E1KoB17ooDLA",
                playlistDescription: "Ambient sounds from cities around the world.",
                playlistId: "PLkmb1BBi8y93GnJ_yClUZei92tCg49Do4",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 49,

            },
            {
                title: "Nature Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/qRTVg8HHzUo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCgM2LaUhy3mSWfKCzJ8ysmYiwv6Q",
                playlistDescription: "Immerse yourself in the serenity of nature for a soothing, 4k ambient experience.",
                playlistId: "PLpEqmyo6EfvKqGFfjS3r8OXZtjKexkikR",
                channelTitle: "Nature Sooundscapes",
                channelImgSrc: "https://yt3.googleusercontent.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Nature_Soundscapes",
                vidCount: 13,

            },
            {
                title: "Rain Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/V_vj7BMawAI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC8qxKnT8LysNMSeYhJ2wwO0-nYIg",
                playlistDescription: "Collection of relaxing rain ambience sounds videos from around the world.",
                playlistId: "PLkmb1BBi8y93GnJ_yClUZei92tCg49Do4",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 46,
            },
            {
                title: "Nature Ambience Sounds",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/3raVUTPAd-w/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZQfehA5iuyiPzh6SdBJsk9dCtvw",
                playlistDescription: "Collection of relaxing nature ambience sounds videos from around the world.",
                playlistId: "PLkmb1BBi8y93qIwNcnuo3e9oyLxc8PVGB",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 35,
            },
            {
                title: "Rain Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/c0_ejQQcrwI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDIMjFPok4MQ53trfOj9U5NdIAs5g",
                playlistDescription: "Relaxing rain sounds for focusing, meditating, sleeping, and calming anxiety.",
                playlistId: "PLvTaXqHhgyZ7XuuhDZtQeTif54Warh0Db",
                channelTitle: "Calmed By Nature",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM5X1aJOEuFHVtUqrKuUYJJ9TGZFGBe4U0KL6hg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@CalmedByNature",
                vidCount: 35,
            },
            {
                title: "Lord of the Rings Music & Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/uBmbI8dzc-M/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCHJeuVTDQpFrGmbdbe5mWnOyoZ5Q",
                playlistDescription: "Step into Middle-Earth and enjoy the sights and sounds of your favorite iconic locations.",
                playlistId: "PLYSqJ3BBUHqhGnPS7yQk0ss3LM58TiYSP",
                channelTitle: "Ambient Worlds",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                vidCount: 35,
            },
            {
                title: "Harry Potter Music and Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/xLwm252AqJ8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDzi3ykbRPFH_HRqTvZ3TOyI69lRw",
                playlistDescription: "Escape into the the Wizarding World of Harry Potter!",
                playlistId: "PLYSqJ3BBUHqho9Af8rZQCfJwiYtNGdzAA",
                channelTitle: "Ambient Worlds",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                vidCount: 40,
            },
            {
                title: "Star Wars Music & Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/83n4pLUhTmk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBd_45I6xQG17TaVSPJTnCZdWHDJQ",
                playlistDescription: "Escape into the the Wizarding World of Harry Potter!",
                playlistId: "PLYSqJ3BBUHqho9Af8rZQCfJwiYtNGdzAA",
                channelTitle: "Ambient Worlds",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                vidCount: 9,
            },
            {
                title: "Star Wars Music & Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/83n4pLUhTmk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBd_45I6xQG17TaVSPJTnCZdWHDJQ",
                playlistDescription: "Escape into the the Wizarding World of Harry Potter!",
                playlistId: "PLYSqJ3BBUHqho9Af8rZQCfJwiYtNGdzAA",
                channelTitle: "Ambient Worlds",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                vidCount: 9,
            },
            {
                title: "Star Wars Music & Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/83n4pLUhTmk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBd_45I6xQG17TaVSPJTnCZdWHDJQ",
                playlistDescription: "Escape into the the Wizarding World of Harry Potter!",
                playlistId: "PLYSqJ3BBUHqho9Af8rZQCfJwiYtNGdzAA",
                channelTitle: "Ambient Worlds",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                vidCount: 9,
            },
        ]
    },
    {
        title: "Archictecture",
        playlists: [
            {
                title: "Open Door: Inside Celebrity Homes",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/D-qQneOnJl0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADKxJSiTHX6Vt_69xRORV_DbvHVg",
                playlistDescription: "Hello World",
                playlistId: "PLpi4YdMCC439sN_5vIza6IfQm0qc-IqPO",
                channelTitle: "Architectural Digest",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                vidCount: 150,
            },
            {
                title: "Walking Tour",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/EuNguMnSKnA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLChHTKsXAKbartzBAC7F3XakBbNsQ",
                playlistDescription: "Hello World",
                playlistId: "PLpi4YdMCC439LJOnJyIgLR98zCazUGNwq",
                channelTitle: "Architectural Digest",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                vidCount: 12,
            },
            {
                title: "An Architect's Own Home",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/J4_rLK7F4fw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7rMhQ_puQrsh8sB2Cl_iiFsoA_w",
                playlistDescription: "Hello World",
                playlistId: "PLirM94SQW73BAPwA09CDbGd6RRMK4SJpp",
                channelTitle: "The Local Project",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                vidCount: 30,
            },
            {
                title: "Tiny Homes and Cabins",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/9Eu0nHapqf0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCks4Pc293qBBzIKMf8ejy6Q76S0g",
                playlistDescription: "Hello World",
                playlistId: "PLirM94SQW73AXi3KRoq3bsGphry4Znoe_",
                channelTitle: "The Local Project",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                vidCount: 12,
            },
            {
                title: "Australian Homes Series",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/dZEgImpC1GI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAVAg1B0o4EhhoStWRdFUhL6jodCg",
                playlistDescription: "Hello World",
                playlistId: "PLirM94SQW73DxCZHkH5uv85utVF_VGZF7",
                channelTitle: "The Local Project",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                vidCount: 184,
            },
            {
                title: "NEVER TOO SMALL Official Playlist",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/bA6C7QvTqZQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKtmnlvwJBpZbWf1_XBuDYcmJG2w",
                playlistDescription: "Hello World",
                playlistId: "PL1WZky7MVeY_6H2ieeVKitXGd3npyPo-g",
                channelTitle: "Never Too Small",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPu1g1VZ5_9vzfGYd9O6p_c0EK3N3Z8TrpRux12Hw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nevertoosmall",
                vidCount: 150,
            },
            {
                title: "Tiny House Tours",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/wAsXkkLumrk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCE1YQe2sTpdeZbkAtTMnWtbaSLbw",
                playlistDescription: "Hello World",
                playlistId: "PL999ZDYL8QbTqnT8PZshZzJa7tat-Vdcj",
                channelTitle: "Architectural Digest",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM49fR69HbYoFhsWkmCsi7SwgDIfrZA3ayVzXM4cw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@livingbig",
                vidCount: 292,
            },
            {
                title: "Une Fille, Un Style | Vogue France",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/EwPiQD1w4uU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCL_IRH-w11yatDduLJsjeq_oIlDw",
                playlistDescription: "Hello World",
                playlistId: "PLVRtRwc2n-r6ToS9OapZq9OilGU3zqrbi",
                channelTitle: "Vogue France",
                channelImgSrc: "https://yt3.googleusercontent.com/zugRK3m-JPWTEds-VSs4ic4IkswQgZFxbY4M0E80vtYzdKv5_jqy8wbjTMWjQvbdqpvZ-1srJA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@VogueFrance",
                vidCount: 150,
            },
        ]
    },
    {
        title: "Art",
        playlists: [
            {
                title: "Art Book Reviews",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/wKjc5GSAcrw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDeAlGiH9RcEm9WP5ovhFyH0cOOrA",
                playlistDescription: "Hello World",
                playlistId: "PLOBH6dux3B0gLfU6SK7IdWeCZMa49H___",
                channelTitle: "Adam Duff LUCIDPIXUL",
                channelImgSrc: "https://yt3.googleusercontent.com/stXTo4OSGjHAwwQ7zwRH8xHF24_jBFmfnyJEn7a9YUBeS_k9xTwdka8J15mL5MFfQ85naI0O6A=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AdamDuffArt",
                vidCount: 36,

            },
            {
                title: "Sketchbook Tours",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/OmLkBQmZQM8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAm1MJt-sbBgIwMGQIpbQlzVWBrQ",
                playlistDescription: "Hello World",
                playlistId: "PLtG4P3lq8RHHXwanyL1qP2OZCy6lQIubD",
                channelTitle: "Proko",
                channelImgSrc: "https://yt3.googleusercontent.com/QJ65R-XtiNccZ8OLfQRo9uJ1H5rujWLt5bF2F1gJpOs9r2Zf4flpiCidYNLVJpws3o6D7k_g_w=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@ProkoTV",
                vidCount: 36,

            },
            {
                title: "Sam Does Art",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/wZxc71tUz8s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVO8isTqAgkELDBZAsTJVV_cZiug",
                playlistDescription: "Hello World",
                playlistId: "PLqjITxHQe6Sgs_p1r1jx6Wj2RYarCFqRp",
                channelTitle: "Sam Does Arts",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM5ZbMDBn9PJevUnYNm-7cNzr44NPGOOXgI8Hct=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@samdoesarts",
                vidCount: 36,

            },
            {
                title: "Great Big Story - Art Stories",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/xMgz61YjoLU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjRWtbDgt0GV4CDjRjVgW5NsynEQ",
                playlistDescription: "Hello World",
                playlistId: "PLpEqmyo6EfvIUMb4z97ohT4GGyy14FDsa",
                channelTitle: "Great Big Story",
                channelImgSrc: "https://yt3.googleusercontent.com/ek2CK7M2HU9SCi7SkN10_1BfP7HpEjXA7lieUdPgamKJYhyJbLezmsj7rF3t6KtTOZl0Zrq1IQ=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@GreatBigStory",
                vidCount: 27,

            },
            {
                title: "3D Render Montages",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/EdCvwmebWN0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArWq2ck_Aub2tg0mWSR1yc4E4rhQ",
                playlistDescription: "Hello World",
                playlistId: "PLFB0oFTSWSYb1mpL9YCFAT1YmSl3G--Ew",
                channelTitle: "pwnisher",
                channelImgSrc: "https://yt3.googleusercontent.com/ER3I3TTJPZ6s7F0ARY1a88touU80pbINHVK8iYD45HC-TgEmcpcQJqVAVNxC4jxjcIGTQ1fe=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@pwnisher",
                vidCount: 10,

            },
            {
                title: "Lunchtime talks | National Gallery",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/YV4YGUAHPJU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAKCbnACrcGCt2-c88HLO9g5_YgWQ",
                playlistDescription: "Hello World",
                playlistId: "PLvb2y26xK6Y5RvnFbi2aZ_KKhaTz7kMB",
                channelTitle: "The National Gallery",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMa-_WXt4n6PJhN2IDYKkPo4QFBftdDqUFz5pjdDm0=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nationalgallerylondon",
                vidCount: 27,

            },
            {
                title: "Narrated Videos",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/v1Mjc4zNfY4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdgrla9B_aypqYqD6a9UI3OpfZlg",
                playlistDescription: "Hello World",
                playlistId: "PLoZ-LEVLUe6b8NamywcV2pai_pqVGn5zs",
                channelTitle: "Baumgartner Restoration",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqNmie5F4kLzvd3u8NiJTVMWR0j8v1CnSwXpMrSY=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BaumgartnerRestoration",
                vidCount: 36,
            },
            {
                title: "Great Art Explained",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/IBcB_dYtGUg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLsrhuZlz8kzcOwffTFXF6pchw4g",
                playlistDescription: "Hello World",
                playlistId: "PLoZ-PLjBkTEtM_Tw_cQi2PXrD9zSdFFsr4NQ5U",
                channelTitle: "Great Art Explained",
                channelImgSrc: "https://yt3.ggpht.com/SVoD_4bbVOt1Nc3ncoDbMq7s-LU87TWovuFlUw3O0wQAKik0lwMwccnCWcp65cHSnZ4SQbuDPCc=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BaumgartnerRestoration",
                vidCount: 32,
            }
        ]
    },
    {
        title: "History",
        playlists: [
            {
                title: "Epic History TV",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/K7lb6KWBanI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAg7bIfY5tljmHe_WHysOttvs__MQ",
                playlistDescription: "Dramatic, fast-moving, fact-packed history videos to help you make sense of epic events that have shaped the modern world.",
                playlistId: "PLUOc2qodFHp8mvnBE_Ya6Bj0HYnRo4XiY",
                channelTitle: "Epic History TV",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                vidCount: 93,
            },
            {
                title: "Napoleonic Wars",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/nDZGL1xsqzs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVtD39mdAG0acFwDBvd2fyWsl4nQ",
                playlistDescription: "",
                playlistId: "PLUOc2qodFHp-mOphKW9RzQLsFTt-IV9RY",
                channelTitle: "Epic History TV",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                vidCount: 28,
            },
            {
                title: "Ancient Egypt",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/ZrJe2Ab2t0Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9leLyG_Eh9mJUdoUVUzevBjAk8g",
                playlistDescription: "",
                playlistId: "PLq0ER3EMJsCEbrCW0lE3COXpQrw3791qH",
                channelTitle: "Odyssey - Ancient History Documentaries",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@odyssey",
                vidCount: 7,
            },
            {
                title: "Rome",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/CU2AOz8sav4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl9frJrxtNp4plAzkcENOoxwSN0Q",
                playlistDescription: "",
                playlistId: "PLq0ER3EMJsCG8kd3sCfFVTkuYXgcykiy9",
                channelTitle: "Odyssey - Ancient History Documentaries",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@odyssey",
                vidCount: 8,
            },
            {
                title: "Legens And Mysteries",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/ysnzl5fdtMI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCCUlrUFU16ddFC8hIrXWtG5lMyaw",
                playlistDescription: "",
                playlistId: "PLq0ER3EMJsCFXxap9t3JNbq1dX",
                channelTitle: "Odyssey - Ancient History Documentaries",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@odyssey",
                vidCount: 11,
            },
            {
                title: "Timeline's Ancient Civilisations",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/RCI28U2TvVs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZPnHpRxmjEtoYH2f1QJfKT2EoVQ",
                playlistDescription: "",
                playlistId: "PLq0ER3EMJsCEbrCW0lE3COXpQrw3791qH",
                channelTitle: "Timeline - World History Documentaries",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPjQK0xKlyZpbWUMzcE5BcJHvArxeKNCki2ijo1Pg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TimelineChannel",
                vidCount: 19,
            },
            {
                title: "Medieval Battles",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/BV5Z_CHbkAw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCC12FXPNGVlK33rDIU0vniXLX0fg",
                playlistDescription: "",
                playlistId: "PLOjUdznmpOjjsJxgmAzwjdsoDomZjGYmc",
                channelTitle: "Baz Battles",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                vidCount: 28,
            },
            {
                title: "Game of Thrones",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/k1zsvHusfPQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBswM110Dk6U6XWHlztR2bQt6B70w",
                playlistDescription: "",
                playlistId: "PLOjUdznmpOjiJQD_rOpw4iX8Vj-AoxGUe",
                channelTitle: "Baz Battles",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                vidCount: 5,
            }
        ]
    },
    {
        title: "Travel",
        playlists: [
            {
                title: "Relaxing Hiking Videos",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/WKcnvPDgifA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQhlIq7mkeUHGT6-QFER1u4-qcUw",
                playlistDescription: "Hello World",
                playlistId: "PLpEqmyo6EfvKJaI7Rl1Y0zvxkPVjqfPwX",
                channelTitle: "Kraig Adams",
                channelImgSrc: "https://yt3.googleusercontent.com/Q5rf5ItB1wumirWCX0cVO7d31Hi4N1B5vIWthJ7Bx8_1KyIAiFXFkGS0CLqBpowSicJMdI32B40=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@kraigadams",
                vidCount: 22,
            },
            {
                title: "Travel Guide - Italy",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/vzU1h61yqQg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCBhjVcy4I1mmQphRbhG1UjDHzvsA",
                playlistDescription: "Hello World",
                playlistId: "PL2203FB5B8E4D4D99",
                channelTitle: "Rick Steves' Europe",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMx_-Mkmuil3vVoHCg6KgDpC-5EUzGr616CwhTg7g=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@ricksteves",
                vidCount: 125,
            },
            {
                title: "Travel Guide - Spain, Portugal & Morocco",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/qI7S3mCIbgQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB8_scT3XGcuUNhtIzIcsZvDFz_8Q",
                playlistDescription: "Spain, Portugal & Morocco fill your days with world-class art, folk life, exotic foods, sunshine, and friendly people.",
                playlistId: "PLAF8618AFFCFBCF3E",
                channelTitle: "Rick Steves' Europe",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMx_-Mkmuil3vVoHCg6KgDpC-5EUzGr616CwhTg7g=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@ricksteves",
                vidCount: 125,
            },
            {
                title: "Travel Guide - Great Britain",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/TjYBM3L437U/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB-w6Vn_o5B0Rs-RA6ErS0tDQBXJQ",
                playlistDescription: "From the grandeur of London, to charming fishing villages that dot the coast, Great Britain is a delight.",
                playlistId: "PL7C576D3DE635344E",
                channelTitle: "Rick Steves' Europe",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMx_-Mkmuil3vVoHCg6KgDpC-5EUzGr616CwhTg7g=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@ricksteves",
                vidCount: 125,
            },
            {
                title: "New York City Ambience",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/F8MN0o6RS9o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCF3DJWwdAlGhhYB0E1KoB17ooDLA",
                playlistDescription: "Collection of relaxing rain ambience sounds videos from around the world.",
                playlistId: "PLkmb1BBi8y93GnJ_yClUZei92tCg49Do4",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 25,
            },
            {
                title: "Switzerland Sounds",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/LFOx-vmYrts/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD4OFjt5qX9h40hloioStMfPM6RsA",
                playlistDescription: "Collection of relaxing rain ambience sounds videos from around the world.",
                playlistId: "PLkmb1BBi8y93p4f17dX8n44V2eJsz",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 8,
            },
            {
                title: "Iceland Sounds",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/SB_fEW1b1K8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAuK_vJlLAr6F5hRLE3m0tjHh6Jig",
                playlistDescription: "Collection of relaxing rain ambience sounds videos from around the world.",
                playlistId: "PLkmb1BBi8y91wpcsj-ECx-IufouKyD1xP",
                channelTitle: "Nomadic Ambience",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                vidCount: 8,
            },
        ]
    },
    {
        title: "Culture",
        playlists: [
            {
                title: "Japan Day in the Life Series by Paolo fromTOKYO",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/YdiWTYkY1uY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLApffPP5IwnwCdcpXW1r-JWLRBrOA",
                playlistDescription: "The Full THR Roundtables",
                playlistId: "PLhKcXp78wsav5hT_0KfjxZuLZupJGlfu6",
                channelTitle: "The Hollywood Reporter",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqP5puBFF-bGNucq0Ksy986PWdyjNJwdDgQIvBqIxQ=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@PaolofromTOKYO",
                vidCount: 39,
            },
            {
                title: "The Full THR Roundtables",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/GuqnPFL8-E8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDKIVE5aqPvZpHmLIcmn7VhvG6v8A",
                playlistDescription: "Watch all the full THR Roundtables",
                playlistId: "PLhKcXp78wsav5hT_0KfjxZuLZupJGlfu6",
                channelTitle: "The Hollywood Reporter",
                channelImgSrc: "https://yt3.googleusercontent.com/7FPGaZ3f81d6IXj-eZwD5_f8UhKNFTMg6jvesjs42nnEwTKrFGnIBGqxbP0QZs2MyAKF2zQHmFA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@hollywoodreporter",
                vidCount: 259,
            },
            {
                title: "Regional Eats",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/ZyZh_FIhGlU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwFZ0JRuVsIJ-rl4mYJFNUY-HI8g",
                playlistDescription: "We travel to a food's area of origin to see how it's made, find out its history.",
                playlistId: "PLW1Mwtj8qAjmvVnVEbBhbcBOAFWlj8mOs",
                channelTitle: "Insider Food",
                channelImgSrc: "https://yt3.googleusercontent.com/my5fZEjea_-N5p8mhqrdNIxghb-KjP9AcH4lQlYzNrRlwzjx3Gbay0JlOCZqJOcp_sTjF3rmBV8=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@InsiderFood",
                vidCount: 82,
            },
            {
                title: "Street Food Icons",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/Fpny0WP8sYw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByNtcd0gC-usJeeaAvmRfi_oB7mQ",
                playlistDescription: "We travel to a food's area of origin to see how it's made, find out its history.",
                playlistId: "PLnPDn1Lb79JFjhC17KjxiFU41SKivZfrW",
                channelTitle: "Munchies",
                channelImgSrc: "https://yt3.googleusercontent.com/JU6HzojvmJwDKybljkQc83LESYZG7NmdPgPo2xXoeHUcUmR98tHjIUhIekgMFGaRyEDgzuv-AA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Munchies",
                vidCount: 82,
            },
            {
                title: "Le Street Style | Vogue France",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/zhcY0M8gBBc/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBkDdeMbK_wc7jX_DpBxpytax28LQ",
                playlistDescription: "We travel to a food's area of origin to see how it's made, find out its history.",
                playlistId: "PLW1Mwtj8qAjmvVnVEbBhbcBOAFWlj8mOs",
                channelTitle: "Vogue France",
                channelImgSrc: "https://yt3.googleusercontent.com/zugRK3m-JPWTEds-VSs4ic4IkswQgZFxbY4M0E80vtYzdKv5_jqy8wbjTMWjQvbdqpvZ-1srJA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@VogueFrance",
                vidCount: 16,
            },
            {
                title: "What Are People Wearing Today",
                playlistThumbnailImgSrc: "https://i.ytimg.com/vi/V8gw9_dLBfM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAKR_5Srx7YM6bdwkUbGThQJWOeAA",
                playlistDescription: "We travel to a food's area of origin to see how it's made, find out its history.",
                playlistId: "PLW1Mwtj8qAjmvVnVEbBhbcBOAFWlj8mOs",
                channelTitle: "icykof",
                channelImgSrc: "https://yt3.googleusercontent.com/DgoBu6nI5sHli_xrW3XS-clzyqdt6ElJvcLKF6HTbo3cviZLgTG8aHqP3_skGq_gt1iZOYuAM9E=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@unknownvlogs",
                vidCount: 82,
            }
        ]
    }
]

export default ytRecsPlaylists