export const defaultThemes: Theme[] = [
    {
        title: "Dark Mode",
        thumbnailImgSrc: "/dark-mode-icon.png",
        sectionDetails: {
            title: "default",
            index: 0
        },
        twinTheme: {
            sectionName: "defaultThemes",
            index: 1,
        },
        properties: {
            isDark: true,
            hasTwin: true,
            isMultiColor: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#0C0C0D",
            secondaryBgColor: "#111111",
            tertiaryBgColor: "#141314",
            fgColor1: "248, 177, 187",
            fgColor2: "163, 182, 255",
            fgColor3: "227, 158, 206",
            fgColor4: "1153, 151, 254",
            textColor1: "255, 255, 255",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#75bef5",
            hoverColor: "#1b1b1b",
            hoverColor2: "",
            tabColor: "#292929",
            tabHighlightColor: "#FFFFFF",
            tabHighlightBoxShadow: "0px -1px 11px rgba(255, 255, 255, 0.21)",
            modalBgColor: "#121212",
            modalFgColor: "#161616",
            dividerColor: "#242424",
            pomBgColor: "#121112",
            pomIconColor: "#858585",
            pomProgressBarFgColor: " linear-gradient(270.59deg, #FF8B9C -10.17%, #E39ECE 12.41%, #A3B6FF 71.86%)",
            pomProgressBarFgBoxShadow: "-1px 0px 23px 6px rgba(187, 173, 237, 0.2)",
            pomProgressBgColor: "#000000",
            pomProgressPlaybackBtnColor: "#F096B8",
            muiscPlayerBgColor: "rgba(153, 153, 153, 0.15)",
            musicProgressFgColor: "",
            musicProgressBgColor: "#0C0D0B",
            navMenuBgColor: "#121112",
            headerElementBgColor: "#141414",
            headerElementTextColor: "255, 255, 255",
            headerElementBorderVal: "0.8px solid #202020",
            navIconColor: "none",
            navIconBgColor: "#1C191C",
            borderVal: "0.9px solid #1C1C1C",
            borderVal2: "1.2px solid #1b1b1b",
            shadowVal: "none",
            shadowVal2: "none",
            sessionBgColor: "#1C1C1C",
            sessionBorderVal: "0.4px solid #262626",
            sessionShadowVal: "none",
            activeSessionItemBorderVal: "0.85px solid #1a1a1a",
            activeSessionItemShadowVal: "none",
            gridItemBorderVal: "0.8px solid #1f1f1f",
            gridItemShadowVal: "none",
            themeToggleBtnBgColor: "#111111",
            iconToggleBtnBgColor: "#3F3F3F",
            highlighterToggleBtnBgColor: "#191919",
            homeVidDropDownTextColor: "none"
        }
    } as DefaultTheme,
    {
        title: "Light Mode",
        thumbnailImgSrc: "/light-mode-icon.png",
        sectionDetails: {
            title: "default",
            index: 1
        },
        twinTheme: {
            sectionName: "defaultThemes",
            index: 0,
        },
        properties: {
            isDark: false,
            hasTwin: true,
            isMultiColor: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FFFEFF",
            secondaryBgColor: "#FAFAFA",
            tertiaryBgColor: "#fdfdfd",
            fgColor1: "248, 177, 187",
            fgColor2: "163, 182, 255",
            fgColor3: "227, 158, 206",
            fgColor4: "1153, 151, 254",
            borderVal: "1px solid rgb(236, 236, 236)",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 4px 13px rgba(0, 0, 0, 0.06)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#FFFFFF",
            sessionBorderVal: "0.6px solid #f0f0f0",
            sessionShadowVal: "0px 4px 4px rgba(0, 0, 0, 0.05)",
            activeSessionItemBorderVal: "1.3px solid #f4f4f4",
            activeSessionItemShadowVal: "none",
            textColor1: "46, 35, 48",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#75bef5",
            hoverColor: "#F1F1F1",
            hoverColor2: "",
            tabColor: "#F2F2F2",
            tabHighlightColor: "#949FFF",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#FFFFFF",
            headerElementBorderVal: "1px solid #EEEEEE",
            headerElementTextColor: "46, 35, 48",
            modalBgColor: "#FAFAFA",
            modalFgColor: "#FFFEFF",
            gridItemBorderVal: "0.7px solid #EAEAEA",
            gridItemShadowVal: "none",
            dividerColor: "#EDEDED",
            pomBgColor: "#E6EAFF",
            pomIconColor: "#CFC4E2",
            muiscPlayerBgColor: "#a3b6ff",
            musicProgressFgColor: "",
            musicProgressBgColor: "#494E7D",
            navMenuBgColor: "#FFFEFF",
            pomProgressBarFgColor: " linear-gradient(270.59deg, #FF8B9C -10.17%, #E39ECE 12.41%, #A3B6FF 71.86%)",
            pomProgressBarFgBoxShadow: "none",
            pomProgressBgColor: "#E6EAFF",
            pomProgressPlaybackBtnColor: "#F096B8",
            navIconColor: "none",
            navIconBgColor: "none",
            themeToggleBtnBgColor: "string",
            iconToggleBtnBgColor: "#CCCBCC",
            highlighterToggleBtnBgColor: "#F5F5F5",
            homeVidDropDownTextColor: "none"
        }
    } as DefaultTheme
]
export const darkColorThemes: Theme[] = [
    {
        title: "Dark Academia",
        isDark: false,
        sectionDetails: {
            title: "dark",
            index: 0
        },
        twinTheme: {
            sectionName: "lightColorThemes",
            index: 7,
        },
        colorPalette: [
            "#241D15", "#564232", "#86684D", "#B8956B", "#B8A086"
        ],
        properties: {
            isDark: true,
            hasTwin: true,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#11100F",
            secondaryBgColor: "#131211",
            tertiaryBgColor: "#131312",
            fgColor1: "212, 163, 115",
            fgColor2: "142, 121, 114",
            fgColor3: "195, 183, 183",
            fgColor4: "195, 183, 183",
            borderVal: "0.7px solid #1D1D1D",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "none",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.04)",
            sessionBgColor: "#232221",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.13)",
            activeSessionItemBorderVal: "1px solid #181818",
            activeSessionItemShadowVal: "none",
            textColor1: "255, 255, 255",
            textColor2: "35, 35, 35",
            themeHighlightBorderColor: "#8a6e60",
            hoverColor: "#252423",
            hoverColor2: "#1A1918",
            tabColor: "#211f1f",
            tabHighlightColor: "#d9b29f",
            tabHighlightBoxShadow: "0px 1px 9px 0px rgba(117, 93, 81, 0.33)",
            headerElementBgColor: "#2F2926",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#131312",
            modalFgColor: "#161515",
            gridItemBorderVal: "0.4px solid #232323",
            gridItemShadowVal: "none",
            dividerColor: "#222222",
            muiscPlayerBgColor: "#2F2926",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#1D1A19",
            pomBgColor: "none",
            pomIconColor: "#DCCBC0",
            pomProgressBarFgColor: "#644D46",
            pomProgressPlaybackBtnColor: "#644D46",
            pomProgressBgColor: "#0A0808",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#131211",
            navIconColor: "#BC9D87",
            navIconBgColor: "#171616",
            themeToggleBtnBgColor: "#121111",
            iconToggleBtnBgColor: "#3F3F3F",
            highlighterToggleBtnBgColor: "#1d1717",
            homeVidDropDownTextColor: "#bc9d87"
        }
    } as ColorTheme,
    // {
    //     title: "Dusk",
    //     isDark: false,
    //     colorPalette: [
    //         "#1A191A", "#252223", "#C69393", "#E6A090", "#EFB9AE"
    //     ],
    //     properties: {

    //     }
    // },
    // {
    //     title: "Sunset",
    //     isDark: false,
    //     colorPalette: [
    //         "#1A191A", "#232225", "#9792CD", "#B5A7F0", "#C8B8F3"
    //     ],
    //     properties: {

    //     }
    // },
    // {
    //     title: "Cumulus",
    //     isDark: false,
    //     colorPalette: [
    //         "#19191A", "#222425", "#959CB6", "#AFB5CA", "#BCCAD8"
    //     ],
    //     properties: {

    //     }
    // },
]
export const lightColorThemes: Theme[] = [
    {
        title: "Olive",
        sectionDetails: {
            title: "light",
            index: 0
        },
        colorPalette: [
            "#72673A", "#A2956E", "#BFB38D", "#D2C7A8", "#DBD5C1"
        ],
        twinTheme: null,
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#ECE7D6",
            secondaryBgColor: "#F0ECDF",
            tertiaryBgColor: "#F4F0E6",
            fgColor1: "248, 177, 187",
            fgColor2: "160, 148, 113",
            fgColor3: "227, 158, 206",
            fgColor4: "1153, 151, 254",
            borderVal: "0.4px solid rgba(178, 178, 178, 0.46)",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 4px 18px 0px rgba(123, 123, 123, 0.07)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#FAF6ED",
            sessionBorderVal: "0.4px solid rgba(164, 164, 164, 0.26)",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #e6e3db",
            activeSessionItemShadowVal: "none",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#CABC94",
            hoverColor: "#F9F5ED",
            hoverColor2: "",
            tabColor: "#E8E2D6",
            tabHighlightColor: "#A39673",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#F0ECDF",
            headerElementBorderVal: "0.9px solid #d3cdba",
            headerElementTextColor: "67, 63, 50",
            modalBgColor: "#F0ECDF",
            modalFgColor: "#f4f1eb",
            gridItemBorderVal: "0.4px solid #D9D3C1",
            gridItemShadowVal: "none",
            dividerColor: "#DBD7CA",
            pomBgColor: "none",
            pomIconColor: "#A2956E",
            muiscPlayerBgColor: "#A09471",
            musicProgressFgColor: "",
            musicProgressBgColor: "#4B4C43",
            navMenuBgColor: "#F0ECDF",
            pomProgressBarFgColor: "#A4946E",
            pomProgressBarFgBoxShadow: "none",
            pomProgressBgColor: "#DED7C5",
            pomProgressPlaybackBtnColor: "#A4946E",
            navIconColor: "#A2956E",
            navIconBgColor: "#ece7d9",
            themeToggleBtnBgColor: "ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#888477"
        }
    } as ColorTheme,
    {
        title: "Basil",
        sectionDetails: {
            title: "light",
            index: 1
        },
        twinTheme: null,
        colorPalette: [
             "#66754C", "#8E9B6D", "#A5AB95", "#D5C7AA", "#FAF5EB"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FFFCF7",
            secondaryBgColor: "#FFFCF6",
            tertiaryBgColor: "#FAF8F2",
            fgColor1: "248, 177, 187",
            fgColor2: "206, 196, 176",
            fgColor3: "206, 196, 176",
            fgColor4: "1153, 151, 254",
            borderVal: "0.4px solid rgba(178, 178, 178, 0.46)",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 4px 18px 0px rgba(123, 123, 123, 0.07)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#CEC4B0",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#8D907C",
            hoverColor: "#F9F5ED",
            hoverColor2: "",
            tabColor: "#f4efe6",
            tabHighlightColor: "#8D907C",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#493a30",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#FFFAEF",
            modalFgColor: "#FFFCF6",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#dedfd8",
            muiscPlayerBgColor: "#8D907C",
            musicProgressFgColor: "",
            musicProgressBgColor: "#45473D",
            pomBgColor: "none",
            pomIconColor: "#CEC4B0",
            pomProgressBarFgColor: "#CEC4B0",
            pomProgressBarFgBoxShadow: "none",
            pomProgressBgColor: "#f1ede5",
            pomProgressPlaybackBtnColor: "#CEC4B0",
            navMenuBgColor: "#FAF5EB",
            navIconColor: "#8d926f",
            navIconBgColor: "#EFEBDD",
            themeToggleBtnBgColor: "ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#8D907C"
        }
    } as ColorTheme,
    {
        title: "Azul",
        sectionDetails: {
            title: "light",
            index: 2
        },
        twinTheme: null,
        colorPalette: [
             "#5E73AF", "#7487BF", "#98A3C4", "#C5CAD8", "#FAF5EB"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#fcf7ed",
            secondaryBgColor: "#FDFAF4",
            tertiaryBgColor: "#FAF8F3",
            fgColor1: "248, 177, 187",
            fgColor2: "120, 135, 179",
            fgColor3: "206, 196, 176",
            fgColor4: "1153, 151, 254",
            borderVal: "0.7px solid #d9d9d9",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 2px 16px 5px rgba(0, 0, 0, 0.06)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "60, 66, 85",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#6678ab",
            hoverColor: "#F9F5EF",
            hoverColor2: "",
            tabColor: "#ede9e0",
            tabHighlightColor: "#6678ab",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#8693b8",
            headerElementBorderVal: "0.4px solid #D5D5D5",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#FAF5EB",
            modalFgColor: "#FDFAF4",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#6678ab",
            musicProgressFgColor: "",
            musicProgressBgColor: "#41485E",
            pomBgColor: "none",
            pomIconColor: "#c7c3b7",
            pomProgressBarFgColor: "#6678ab",
            pomProgressPlaybackBtnColor: "#6678ab",
            pomProgressBgColor: "#CCCCCC",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#faf5eb",
            navIconColor: "#6678ab",
            navIconBgColor: "#fffbf4",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#6678ab"
        }
    } as ColorTheme,
    {
        title: "Vert",
        sectionDetails: {
            title: "light",
            index: 3
        },
        twinTheme: null,
        colorPalette: [
             "#508D6C", "#739984", "#93B6A3", "#C1C9C0", "#FAF5EB"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#fcf7ed",
            secondaryBgColor: "#FDFAF4",
            tertiaryBgColor: "#FAF8F3",
            fgColor1: "248, 177, 187",
            fgColor2: "100, 142, 119",
            fgColor3: "206, 196, 176",
            fgColor4: "1153, 151, 254",
            borderVal: "0.7px solid #d9d9d9",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 2px 16px 5px rgba(0, 0, 0, 0.06)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "49, 57, 38",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#648E77",
            hoverColor: "#F9F5EF",
            hoverColor2: "",
            tabColor: "#ede9e0",
            tabHighlightColor: "#648E77",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#739382",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#FAF5EB",
            modalFgColor: "#FDFAF4",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#648E77",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#374B40",
            pomBgColor: "none",
            pomIconColor: "#c7c3b7",
            pomProgressBarFgColor: "#648E77",
            pomProgressPlaybackBtnColor: "#648E77",
            pomProgressBgColor: "#CCCCCC",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#faf5eb",
            navIconColor: "#648E77",
            navIconBgColor: "#fffbf4",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#739382"
        }
    } as ColorTheme,
    {
        title: "Earth",
        sectionDetails: {
            title: "light",
            index: 4
        },
        twinTheme: null,
        colorPalette: [
            "#979687", "#C0BEA6", "#D0CCC2", "#E4BAA2", "#E9D3C5"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#fcf7ed",
            secondaryBgColor: "#FDFAF4",
            tertiaryBgColor: "#FAF8F3",
            fgColor1: "248, 177, 187",
            fgColor2: "197, 193, 185",
            fgColor3: "197, 193, 185",
            fgColor4: "1153, 151, 254",
            borderVal: "0.7px solid #d9d9d9",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 2px 16px 5px rgba(0, 0, 0, 0.06)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "60, 66, 85",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#C7C4AB",
            hoverColor: "#F9F5EF",
            hoverColor2: "",
            tabColor: "#ede9e0",
            tabHighlightColor: "#CFAB96",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#FFFCF7",
            headerElementBorderVal: "0.4px solid #D5D5D5",
            headerElementTextColor: "60, 66, 85",
            modalBgColor: "#FAF5EB",
            modalFgColor: "#FDFAF4",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#CFAB96",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#CCD9E3",
            pomBgColor: "none",
            pomIconColor: "#C5C1B9",
            pomProgressBarFgColor: "#C5C1B9",
            pomProgressPlaybackBtnColor: "#C5C1B9",
            pomProgressBgColor: "#EDEDED",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#C7C4AB",
            navIconColor: "#FFFFFF",
            navIconBgColor: "#CFCCB3",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#8A8D96"
        }
    } as ColorTheme,
    {
        title: "Summer",
        sectionDetails: {
            title: "light",
            index: 5
        },
        twinTheme: null,
        colorPalette: [
            "#EBD1AE", "#F2F0E3", "#D7D9C7", "#ECE6C4", "#C2CAB2"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: true,
            isHeaderElementTextLight: true,
            primaryBgColor: "#F9F4EF",
            secondaryBgColor: "#FFFCF9",
            tertiaryBgColor: "#FDFCF8",
            fgColor1: "212, 163, 115",
            fgColor2: "212, 163, 115",
            fgColor3: "235, 209, 174",
            fgColor4: "1153, 151, 254",
            borderVal: "0.7px solid #d9d9d9",
            borderVal2: "1px solid rgb(210 210 210 / 10%)",
            shadowVal: "0px 2px 16px 5px rgba(0, 0, 0, 0.06)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.03)",
            sessionBgColor: "#F7F3EE",
            sessionBorderVal: "0.4px solid #DDD",
            sessionShadowVal: "none",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "28, 36, 29",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#B3C0A1",
            hoverColor: "#F4F3F1",
            hoverColor2: "#E9E8E8",
            tabColor: "#f5f0e5",
            tabHighlightColor: "#D4A373",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#B3C0A1",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#F9F4EF",
            modalFgColor: "#FFFCF9",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#B3C0A1",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#CCD9E3",
            pomBgColor: "none",
            pomIconColor: "#E2C8AE",
            pomProgressBarFgColor: "#D4A373",
            pomProgressPlaybackBtnColor: "#D4A373",
            pomProgressBgColor: "#faf1e9",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#F9F4EF",
            navIconColor: "#B3C0A1",
            navIconBgColor: "#F0ECE6",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#F9F4EF"
        }
    } as ColorTheme,
    {
        title: "Pearl",
        sectionDetails: {
            title: "light",
            index: 6
        },
        twinTheme: null,
        colorPalette: [
            "#897D7D", "#A59B9B", "#D4C9C9", "#E4D8D8", "#FEFAF9"
        ],
        properties: {
            isDark: false,
            hasTwin: false,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FEFAF9",
            secondaryBgColor: "#FFFFFF",
            tertiaryBgColor: "#FFFFFE",
            fgColor1: "212, 163, 115",
            fgColor2: "195, 183, 183",
            fgColor3: "195, 183, 183",
            fgColor4: "195, 183, 183",
            borderVal: "0.7px solid #d9d9d9",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 2px 16px 5px rgba(0, 0, 0, 0.1)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.04)",
            sessionBgColor: "#DACDCD",
            sessionBorderVal: "0.4px solid rgba(132, 132, 132, 0.26)",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            activeSessionItemBorderVal: "0.4px solid #DCDCDC",
            activeSessionItemShadowVal: "none",
            textColor1: "52, 42, 42",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#D8CACA",
            hoverColor: "#F7F6F5",
            hoverColor2: "#F9F5F4",
            tabColor: "#f5eeee",
            tabHighlightColor: "#D8CACA",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#C3B7B7",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#F9F4EF",
            modalFgColor: "#FFFCF9",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "none",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#D8CACA",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#6E6868",
            pomBgColor: "none",
            pomIconColor: "#C3B7B7",
            pomProgressBarFgColor: "#C3B7B7",
            pomProgressPlaybackBtnColor: "#C3B7B7",
            pomProgressBgColor: "#F5F1F1",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#FEFAF9",
            navIconColor: "#C3B7B7",
            navIconBgColor: "#F7F1F1",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            homeVidDropDownTextColor: "#C3B7B7"
        }
    } as ColorTheme,
    {
        title: "Light Academia",
        isDark: false,
        sectionDetails: {
            title: "light",
            index: 7
        },
        twinTheme: {
            sectionName: "darkColorThemes",
            index: 0,
        },
        colorPalette: [
            "#86684D", "#B8956B", "#B69F86", "#DDCEBF", "#FCF2E9"
        ],
        properties: {
            isDark: false,
            hasTwin: true,
            isMultiColor: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FFFDF7",
            secondaryBgColor: "#FFFFFF",
            tertiaryBgColor: "#FFFFFE",
            fgColor1: "212, 163, 115",
            fgColor2: "189, 159, 138",
            fgColor3: "195, 183, 183",
            fgColor4: "195, 183, 183",
            borderVal: "0.4px solid rgba(178, 178, 178, 0.46)",
            borderVal2: "1px solid rgba(79, 79, 79, 0.1)",
            shadowVal: "0px 4px 18px 0px rgba(123, 123, 123, 0.07)",
            shadowVal2: "0px 5px 9px rgba(0, 0, 0, 0.04)",
            sessionBgColor: "#E1D0C4",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.06)",
            activeSessionItemBorderVal: "1px solid #efefef",
            activeSessionItemShadowVal: "none",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            themeHighlightBorderColor: "#D8CACA",
            hoverColor: "#F7F6F5",
            hoverColor2: "#F9F5F4",
            tabColor: "#F7F6F5",
            tabHighlightColor: "#877765",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#baa595",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            modalBgColor: "#FEFAF9",
            modalFgColor: "#FFFFFF",
            gridItemBorderVal: "0.4px solid #D5D5D5",
            gridItemShadowVal: "0px 4px 18px 0px rgba(84, 84, 84, 0.06)",
            dividerColor: "#ddddde",
            muiscPlayerBgColor: "#D8CACA",
            musicProgressFgColor: "#FFFFFF",
            musicProgressBgColor: "#6E6868",
            pomBgColor: "none",
            pomIconColor: "#DCCBC0",
            pomProgressBarFgColor: "#BD9F8A",
            pomProgressPlaybackBtnColor: "#BD9F8A",
            pomProgressBgColor: "#F5F1F1",
            pomProgressBarFgBoxShadow: "none",
            navMenuBgColor: "#FFFDF7",
            navIconColor: "#BC9D87",
            navIconBgColor: "#FAF5F0",
            themeToggleBtnBgColor: "#FAF5F0",
            iconToggleBtnBgColor: "#E3D8CC",
            highlighterToggleBtnBgColor: "#ffffff",
            homeVidDropDownTextColor: "#BC9D87"
        }
    } as ColorTheme,
    // {
    //     title: "Pearl",
    //     isDark: false,
    //     colorPalette: [
    //          "#897D7D", "#A59B9B", "#D4C9C9", "#E4D8D8", "#FEFAF9"
    //     ],
    //     properties: {

    //     }
    // },
    // {
    //     title: "Dark Academia",
    //     isDark: false,
    //     colorPalette: [
    //          "#2B1409", "#4E311A", "#7D5D4B", "#9E856D", "#B19F88"
    //     ],
    //     properties: {

    //     }
    // },
]
export const imageThemes = [
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg/320px-Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg/2560px-Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg",
        title: "Indians Spear Fishing",
        artist: "Albert Bierstadt"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Home_in_the_Woods_1847_Thomas_Cole.jpeg/320px-Home_in_the_Woods_1847_Thomas_Cole.jpeg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/8/89/Home_in_the_Woods_1847_Thomas_Cole.jpeg",
        title: "Home in the Woods",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg/320px-Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/9/94/Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg",
        title: "Venice, from the Porch of Madonna della Salute",
        artist: "J.M.W. Turner"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg",
        title: "Savage State",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg",
        title: "The Arcadian or Pastoral State",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg/320px-Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg/2560px-Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg",
        title: "Consummation",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg",
        title: "Destruction",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg",
        title: "Desolation",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg/320px-Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg/2560px-Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg",
        title: "Dream of Arcadia",
        artist: "Thomas Cole"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg/320px-Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg/2560px-Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg",
        title: "Ship on Stormy Seas",
        artist: "Ivan Aivazovsky"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/500px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg",
        title: "Water Lillies - 1906",
        artist: "Claude Monet"
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg/307px-Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg",
        title: "Waterlilies ",
        artist: "Claude Monet"
    },
    {
        thumbnailImgSrc: "https://pbs.twimg.com/media/Ea2ATpWUwAAwzvR?format=jpg&name=large",
        fullImgSrc: "https://pbs.twimg.com/media/Ea2ATpWUwAAwzvR?format=jpg&name=large",
        title: "Howl's Moving Castle",
        artist: "Studio Gibhli"
    },
    {
        thumbnailImgSrc: "https://wallpapers.com/images/hd/spirited-away-house-on-an-island-hvwghkdhxqbjzprj.webp",
        fullImgSrc: "https://wallpapers.com/images/hd/spirited-away-house-on-an-island-hvwghkdhxqbjzprj.webp",
        title: "Spirited Away",
        artist: "Studio Gibhli"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1466350380309-a09bb7347af9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1466350380309-a09bb7347af9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Manhattan Bridge",
        artist: "Hieu Vu Minh (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1451186859696-371d9477be93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1451186859696-371d9477be93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2673&q=80",
        title: "Prince Regent National Park",
        artist: "NASA (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2711&q=80",
        title: "Space",
        artist: "NASA (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1581610186406-5f6e9f9edbc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1581610186406-5f6e9f9edbc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Dunes",
        artist: "Daniel Olah (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1644322749926-66ac55e2913e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1644322749926-66ac55e2913e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        title: "Blood Meridian",
        artist: "George Diama (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1538435740860-67bd8f4e8eb8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1538435740860-67bd8f4e8eb8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2728&q=80",
        title: "Foggy Days",
        artist: "Justin Kauffman (Unsplash)"
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1532032659282-dc3fe9336831?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1532032659282-dc3fe9336831?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Mt Hood Under the Stars",
        artist: "Clint MCKoy (Unsplash)"
    },
]
export const ambientVideos = [
    {
        title: "Mount Shuksan",
        vidUrl: "https://www.youtube.com/watch?v=qRTVg8HHzUo",
        thumbnailSrc: "https://i.ytimg.com/vi/qRTVg8HHzUo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCgM2LaUhy3mSWfKCzJ8ysmYiwv6Q",
        channelName: "Nature Soundscapes",
        channelImgSrc: "https://yt3.ggpht.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Hawaii Sunrise",
        vidUrl: "https://www.youtube.com/watch?v=Fz6tH7cTB5M",
        thumbnailSrc: "https://i.ytimg.com/vi/Fz6tH7cTB5M/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCLgi8_QZZUkgV-OntxQ9J2GoJBVA",
        channelName: "Nature Soundscapes",
        channelImgSrc: "https://yt3.ggpht.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Fall Lake",
        vidUrl: "https://www.youtube.com/watch?v=gwE5dGJ_KI0",
        thumbnailSrc: "https://i.ytimg.com/vi/gwE5dGJ_KI0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCCfgYIiku7WbYntiz8YyuV98X13Q",
        channelName: "Nature Soundscapes",
        channelImgSrc: "https://yt3.ggpht.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Rain in Forest",
        vidUrl: "https://www.youtube.com/watch?v=4LeyBbDBvQQ",
        thumbnailSrc: "https://i.ytimg.com/vi/4LeyBbDBvQQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBeewEvZCuZSjksjzh1C2C6NUFr4w",
        channelName: "Nature Soundscapes",
        channelImgSrc: "https://yt3.ggpht.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Storm in Forest",
        vidUrl: "https://www.youtube.com/watch?v=XtDwPLk8EgI",
        thumbnailSrc : "https://i.ytimg.com/vi/XtDwPLk8EgI/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_g6AArgIigIMCAAQARg0IGUoXjAP&rs=AOn4CLAl8f0dt8H-4oi5xHkofaGxvHM-Ng",
        channelName: "Relaxing Ambience ASMR",
        channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMEOjK50czS5qb9_MCdoHcXfHshijmjDWblqATP=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Kapalua Beach, Maui, Hawaii",
        vidUrl: "https://www.youtube.com/watch?v=KM6K6Mz13uA",
        thumbnailSrc: "https://i.ytimg.com/vi/KM6K6Mz13uA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBbEdwf3JixlHb5E-K_b-zGvtqH0Q",
        channelName: "Nature Soundscapes",
        channelImgSrc: "https://yt3.ggpht.com/SWhM3bV2uPbAMb-Qx9F3pxT5EuDCRkFtlrCC0uxvHuPigTXQDtJhhOSu8BiP2tmLfKKYb4f-Nw=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Study Room with Rain",
        vidUrl: "https://www.youtube.com/watch?v=Jvgx5HHJ0qw",
        thumbnailSrc: "https://i.ytimg.com/vi/Jvgx5HHJ0qw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQDhCWJ0TlZkeHq45cZDM4kpPEiA",
        channelName: "Cosmic Report",
        channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqOOAu-iCDlYmTm-UaNKeeqbItrYTVs8Q-BpO-BQ=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Reading Nook",
        vidUrl: "https://www.youtube.com/watch?v=Ol93KaRhrRM",
        thumbnailSrc: "https://i.ytimg.com/vi/Ol93KaRhrRM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDyv-qI-6kRJodCK_4zqvy6l9dYpg",
        channelName: "Cosmic Report",
        channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqOOAu-iCDlYmTm-UaNKeeqbItrYTVs8Q-BpO-BQ=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Minecraft Calm Ambience",
        vidUrl: "https://www.youtube.com/watch?v=CSk9Ozs5Kpg",
        thumbnailSrc: "https://i.ytimg.com/vi/CSk9Ozs5Kpg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBOHjSUJP5PevquL2Ms_S2MDboosg",
        channelName: "Craft Therapy",
        channelImgSrc: "https://yt3.ggpht.com/43H3Ejti7HaW9VFtGAvl1I7tDSEr7oUynApD4j9XE86H8i1-m1ZUrWBxPUU2E2Xe-Vn_kSc8=s88-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Warm hideout duing a Stormy Night",
        vidUrl: "https://www.youtube.com/watch?v=2PywKRQhK2g",
        thumbnailSrc: "https://i.ytimg.com/vi/2PywKRQhK2g/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBW69EqIfsOHOIQf8MsIdWLu6Ozhw",
        channelName: "dreamysound",
        channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqO5PB-S_w-J0KXq4bVHbf0iMDi6TSs0b3TqiQT_Zg=s176-c-k-c0x00ffffff-no-rj"
    },
    {
        title: "Raining in Osaka",
        vidUrl: "https://www.youtube.com/watch?v=q55qNEKQLG0",
        thumbnailSrc: "https://i.ytimg.com/vi/q55qNEKQLG0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPskftIDJ3U7gnbkcBwXcW_urnYQ",
        channelName: "Lofi Music",
        channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqMwzOUdfgOvtBXnt0MYP4IuHQmxHd8T2Lwo4mcZ=s88-c-k-c0x00ffffff-no-rj"
    },
]