const YT_PLAYLIST_GROUPS: YoutubePlaylistGroup[] = [
    {
        title: "Lofi / Chill",
        playlists: [
            {
                id: "PLTlW3nrfe71SiLOgo5nTEwQ5XLDBkCgBw",
                title: "lofi girl",
                description: "Enjoy a compilation of Lofi Girl's most beloved videos and live streams for chill vibes.",
                vidCount: 17,
                channelId: "",
                channelTitle: "Lofi Girl",
                thumbnailURL: "https://i.ytimg.com/vi/zFhfksjf_mY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBQgYKl48s3nIAYnxSDbiy65PL42g",
                channelImgSrc: "https://yt3.googleusercontent.com/gY8H7K-3Eg3olVftRBiqqFe-N5d9Rx90jAsrfQuxDa4m32Wm-kWK6AQJhwchvYLf-H4EjGhCSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@LofiGirl",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71Qzen8aBUryHJgv9dZa8XHv",
                title: "Studio Ghibli",
                description: "The magic of Studio Ghibli, mixed into a visual & sonic experience.",
                vidCount: 14,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/Sx4xVyXHl60/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAyg77XoyF7_I9aONds6qEiFhDD4g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71TBc9e7QcO2_L_VOjs7Fjfy",
                title: "Romantic Chill",
                description: "For the romantics of the classical / dark-academia aesthetics.",
                vidCount: 17,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/03IAR5O07h0/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhjIGUoKzAP&rs=AOn4CLCy8NZG0EvdWRN2v6N1cNLFu4Ue2g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QGDL4exacmUwyriixlc2K7",
                title: "Coding Lofi CHill",
                description: "Because debugging is less painful with chill beats :)",
                vidCount: 12,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/_ITiwPMUzho/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCdFE2e_RZb_9O5SPsNeuI9HiSctA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71R4__x5h3omOh8FXf1nf8Up",
                title: "Gaming Relax & Chill",
                description: "Escape into tranquility with melodies from Zelda, Animal Crossing, and other Nintendo favorites in this calming playlist.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Mutliple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/EdHGrnuCEo4/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhdIGUoUTAP&rs=AOn4CLCRjy5XbgxBm3xltMq0G7SdSXInqQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71Sx6SiZbz7LwZ1fJi5BVcZa",
                title: "Lofi Chill",
                description: "Explore a captivating collection of lo-fi and jazz playlists, perfect for cozy moments and relaxing vibes.",
                vidCount: 18,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/TYCBicKyVhs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAxH2OcNzH6KHMd839rWzwG0r8koA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QuWLeoSF_EQ3OkwfVua5bP",
                title: "Pokémon Chill",
                description: "From Kanto's beginnings to the wonders of Galar and all the adventures that link them, experience the magic of Pokémon's cherished music.",
                vidCount: 21,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/VToyayJ4u2k/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IFooFDAP&rs=AOn4CLCdGv_nCNakJpACY7yO4efzfEeOzg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QicutfuzVOH7jIEc-5HHjF",
                title: "Minecraft Ambience",
                description: "Nostalgic ambience, peaceful gameplay, & fan-made mixes of the iconic soundtrack.",
                vidCount: 17,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/ANkxRGvl1VY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAsueBQ4bMBQPAfcpz3O02TV-briA",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71Qdt9F30kXuUboW7bJdmtJy",
                title: "Anime Chill",
                description: "Unwind to the calming melodies and sounds of anime.",
                vidCount: 21,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/TdBSoy9F9NA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB6SDroyCAho5lVOce12jF1lndi5A",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QSdeLCRIk9iPOodZZMksx2",
                title: "Disney / Pixar Chill",
                description: "Unwind in the beloved worlds of Disney & Pixar.",
                vidCount: 9,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/UP8OO7g07B4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUNjVzaM_omS1oLQGSjbxQ9E6jog",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
        ]
    },
    {
        title: "Eclectic Mix",
        playlists: [
            { 
                id: "PLTlW3nrfe71Qp2mZn7GVJYeC6ZGIZJQHE",
                title: "Eclectic Grooves Sessions.",
                description: "MAJ and Friends explore rare grooves around the world on vinyl.",
                vidCount: 20,
                channelId: "",
                channelTitle: "My Analog Journal",
                thumbnailURL: "https://i.ytimg.com/vi/Beld090NIoo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDY32Pw8QZqFOdxA03H59IVQi68gA",
                channelImgSrc: "https://yt3.googleusercontent.com/INosGb8ZVriDTJNZv_1E9Pw_TiPx0iddBfnFcSToUYDqqqINXDXLAHT0pJqJ5PuZqznx1XUUoA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@MyAnalogJournal",
                firstVidId: null
            },
            { 
                id: "PLTlW3nrfe71SVLqTz8Xrk_bJOXeFSrtKz",
                title: "NPR Tiny Desk Live Performances.",
                description: "Live, intimate artistry from the famous NPR Tiny Desk Concerts.",
                vidCount: 21,
                channelId: "",
                channelTitle: "NPR Music",
                thumbnailURL: "https://i.ytimg.com/vi/uwUt1fVLb3E/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA0RnQkpSErBTz9d3YXJrYrG3LN3g",
                channelImgSrc: "https://yt3.googleusercontent.com/INosGb8ZVriDTJNZv_1E9Pw_TiPx0iddBfnFcSToUYDqqqINXDXLAHT0pJqJ5PuZqznx1XUUoA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nprmusic",
                firstVidId: null
            },
            { 
                id: "UULP2Qw1dzXDBAZPwS7zm37g8g",
                title: "Colors Shows.",
                description: "Minimalistic shows from burgeoning musicians.",
                vidCount: 800,
                channelId: "",
                channelTitle: "COLORS",
                thumbnailURL: "https://thisisrnb.com/wp-content/uploads/2018/04/Jorja-Smith-Colors.jpg",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@COLORSxSTUDIOS",
                firstVidId: null
            },
            { 
                id: "PLTlW3nrfe71T40CwkmwP5zmR02roT7EEn",
                title: "Live House Mixes",
                description: "Live house mixes for non-stop, immersive electronic dance vibes.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/z-8vVxz-If0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC2KHvrENtncWgQRhC7_3f9ep76eg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            { 
                id: "PLTlW3nrfe71RWu84YggxarmAm5IdyBUOk",
                title: "Jazz Gems & Classics",
                description: "An eclectic jazz mix, from modern to classics.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://upload.wikimedia.org/wikipedia/en/f/f8/Nala_Sinephro_-_Space_1.8.png",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            // { 
            //     id: "PLpEqmyo6EfvLxItVKqjJpZOS8RChsWv18",
            //     title: "Eclectic Mixes",
            //     description: "Live or in-studio. Pop, funk, jazz, lofi, or indie. A little bit of everything for diverse tastes.",
            //     vidCount: 15,
            //     channelId: "",
            //     channelTitle: "Multiple Authors",
            //     thumbnailURL: "https://i.ytimg.com/vi/AmmFD2OIs_k/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBoz9W8WqJcHGhODrLY6598rAppaw",
            //     channelImgSrc: "",
            //     channelURL: "",
            //     firstVidId: null
            // },
            { 
                id: "PLTlW3nrfe71RF4KvL9pkfhLk53nRPnO6a",
                title: "Ambient & Electronic",
                description: "Tranquil soundscapes from seminal works to eclectic gems.",
                vidCount: 15,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i1.sndcdn.com/artworks-qYI9UYzvUBEgeCaz-kTzhPg-t500x500.jpg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            }
        ]
    },
    {
        title: "Study with Me",
        playlists: [
            {
                id: "PLr5OsF2umninLmW-yux0oONqNaQiIpJhw",
                title: "🎸Study with Calm Lofi/Quiet Jazz - Pomodoro Timer/Study/Work",
                description: "Study and work with many calm lofi track and quiet jazz music.",
                vidCount: 10,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/grBFMP3HDZA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAGAboCwXsa6WC-fZvCc9atdetYA",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QNhPlrzUo0yr_4amhoJx9K",
                title: "Scenic Study with Me",
                description: "Study with me from cool desk setups with scenic views and chill music. ",
                vidCount: 19,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/vC4dLeqnvAw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAH0GWr0Nf2U1vhPmQ7icFHVzXocw",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLmWo-cY6xKJbFIhZZZ-dm599XwucdH6gW",
                title: "Real Time Study With Me",
                description: "Enjoy these real time study with me videos to boost your productivity with me :)",
                vidCount: 14,
                channelId: "",
                channelTitle: "Kharma Medic",
                thumbnailURL: "https://i.ytimg.com/vi/fJP7c8xt1n4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADBddEjw38mdfAOgxIzPZjbvLV_w",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqNTfqDJWJCGaH1_SDvNveiG2xDmlsif8XWM3UaBCg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@KharmaMedic",
                firstVidId: null
            },
            {
                id: "PLr5OsF2umninjc42Ia_bzEjKKi9QgHaWU",
                title: "🎧Study with Music - Pomodoro Timer/Study/Work",
                description: "Study with productivity guru \"Abao in Tokyo\" while listenting to some chill tunes.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/sca4VG9b0NY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCzrqQ5S5zh5StvkhR1jB1Pvl4Hgw",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLr5OsF2umnimZ5DUoXnMaKmqa8CwUTb3z",
                title: "Ambient version - Pomodoro Timer/Study/Work",
                description: "Study and work with Sound of Rain, firewood, and environment.",
                vidCount: 20,
                channelId: "",
                channelTitle: "Abao in Tokyo",
                thumbnailURL: "https://i.ytimg.com/vi/UwQp8vOlD14/hqdefault.jpg?sqp=-oaymwEbCMQBEG5IVfKriqkDDggBFQAAiEIYAXABwAEG&rs=AOn4CLCXtNcd2qtxhU09b3J3nbnyAG13PA",
                channelImgSrc: "https://yt3.googleusercontent.com/NrIEzYVk5mBH9yRIefVDnvyD7YQpvbmOUx-LRNaC7KCc1DQ82B-bvURmZbEhZoCllobJjCBq=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@abaointokyo",
                firstVidId: null
            },
            {
                id: "PLdoPDZp9cQnVTyZLzSG91bqEylKwfkpbj",
                title: "Complete Study With Me Playlist",
                description: "This playlist contains all my study with me videos for your convenience!",
                vidCount: 0,
                channelId: "",
                channelTitle: "The Strive Studies",
                thumbnailURL: "https://i.ytimg.com/vi/pRKGH8soIbk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3BzTT05ZeQo3poVT9F9TIvWriYA",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqNS1mtOUxWDpE8rE1Jb2p87ZIErrTCHs56aERkk=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheStriveStudies",
                firstVidId: null
            },
        ]
    },
    {
        title: "Ambience",
        playlists: [
            {
                id: "PLpEqmyo6EfvJseQSBPD78gFiwgI6t9p1K",
                title: "Nature Docs",
                description: "Find serenity in Earth's natural treasures, from the heart of the Amazon Rain Forest to the vast stretches of the African Savannah.",
                vidCount: 11,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/JkaxUblCGz0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCHAgPno9ZlrIdpdJ1IjPcT0CsrcQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71TklS6p1JBCTgkL1RqI7nBV",
                title: "Nature Relaxation",
                description: "The serenity of nature in a soothing, 4k ambient experience.",
                vidCount: 19,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/B_8bbKn3amE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCtRXwToQ_BcNfIwtDYg9D-N2OMdg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71SMAnbHgRrm-G7eCiMO9qLx",
                title: "Weather Ambience",
                description: "Relax to the calming sounds of rain, thunder, snow, and more.",
                vidCount: 10,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/SnUBb-FAlCY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAAUNSRxvRChtlMqz36pS4mypK_6g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKJaI7Rl1Y0zvxkPVjqfPwX",
                title: "Kraig Adams Hiking Videos",
                description: "Experience some of the world's pretties natural wonders with Kraid Adams' theraputic hiking videos.",
                vidCount: 22,
                channelId: "",
                channelTitle: "Kraig Adams",
                thumbnailURL: "https://i.ytimg.com/vi/WKcnvPDgifA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQhlIq7mkeUHGT6-QFER1u4-qcUw",
                channelImgSrc: "https://yt3.googleusercontent.com/Q5rf5ItB1wumirWCX0cVO7d31Hi4N1B5vIWthJ7Bx8_1KyIAiFXFkGS0CLqBpowSicJMdI32B40=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@kraigadams",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QBw6h3hPy23w5Nw8AmElb_",
                title: "City Ambience",
                description: "Ambient sounds from cities around the world.",
                vidCount: 8,
                channelId: "",
                channelTitle: "Nomadic Ambience",
                thumbnailURL: "https://i.ytimg.com/vi/sBtYWK817-0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA1oTe3bknrb7fvx76rYxkpIuyuRg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOr7XmI5VtjkmGkcrNtf_6cPLX0tsk94QOEJnGZSw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@NomadicAmbience",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QjvbI1d6q9lTz5d0tmN3zF",
                title: "Middle Earth Ambience",
                description: "Step into Middle-Earth and enjoy the sights and sounds of your favorite iconic locations.",
                vidCount: 14,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/UpeYqEeIBO4/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARhlIFsoSjAP&rs=AOn4CLBk3FLmYL8Mp2kGeMHgeTBWUNvjtg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71T3rauOjTtMi164cECkr4-J",
                title: "Harry Potter Ambience",
                description: "Escape into the the Wizarding World of Harry Potter!",
                vidCount: 10,
                channelId: "",
                channelTitle: "Ambient Worlds",
                thumbnailURL: "https://i.ytimg.com/vi/pQdTu0IeVho/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA9CmDigiNZto1X2xjiGUQuAHN4iQ",
                channelImgSrc: "https://yt3.ggpht.com/ytc/AGIKgqPonRm9_hPy4ZNSCP-Oh9wfwrtACCF7EzdcuC2IYg=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AmbientWorlds",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71RpZbGmZQHm4W4RCxrRSd0M",
                title: "Star Wars Music & Ambience",
                description: "Atmospheric soundscapes from a distant galaxy, far, far away.",
                vidCount: 8,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/UJ4e4XVQQcY/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_gmAAtAFigIMCAAQARh_IB4oMDAP&rs=AOn4CLCq16EGg2K-Jqfb39hxphVYO-wqbg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
        ]
    },
    {
        title: "Archictecture",
        playlists: [
            {
                id: "UULPgxg48_pay4R67s-7WOgWFA",
                title: "Local Project Popular Videos",
                description: "The Local Project's amazing house tours that explores architecture and interior design stories across Australia, New Zealand, and North America.",
                vidCount: 184,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/dZEgImpC1GI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAVAg1B0o4EhhoStWRdFUhL6jodCg",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PLirM94SQW73BAPwA09CDbGd6RRMK4SJpp",
                title: "An Architect's Own Home",
                description: "Tours of homes designed by the owners themselves.",
                vidCount: 30,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/J4_rLK7F4fw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLA7rMhQ_puQrsh8sB2Cl_iiFsoA_w",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PLirM94SQW73AXi3KRoq3bsGphry4Znoe_",
                title: "Tiny Homes and Cabins",
                description: "Explore cozy living with stunning tiny homes and cabins.",
                vidCount: 12,
                channelId: "",
                channelTitle: "The Local Project",
                thumbnailURL: "https://i.ytimg.com/vi/9Eu0nHapqf0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCks4Pc293qBBzIKMf8ejy6Q76S0g",
                channelImgSrc: "https://yt3.googleusercontent.com/NhCDTmydHHsvQKhwoknxIGAztUNtyi9CQg4HI3gt70Z_9f3BD9etb_uB4a5V2AhWJ2B6Tl1awbE=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TheLocalProject",
                firstVidId: null
            },
            {
                id: "PLpi4YdMCC439LJOnJyIgLR98zCazUGNwq",
                title: "Walking Tours",
                description: "Explore world famous cultural sites from Tokyo to the Côte d'Azure while staying cozy in your PJs!",
                vidCount: 12,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/EuNguMnSKnA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLChHTKsXAKbartzBAC7F3XakBbNsQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            },
            {
                id: "PLpi4YdMCC439sN_5vIza6IfQm0qc-IqPO",
                title: "Open Door: Inside Celebrity Homes",
                description: "Visit the extravagant homes of your favorite athletes, artists, musicians, & actors.",
                vidCount: 150,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/D-qQneOnJl0/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLADKxJSiTHX6Vt_69xRORV_DbvHVg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMlG0_fNgw1y0MdSRE6rnc9lNUsK_3Igg_1nu7Fh-4=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            },
            {
                id: "UULF_zQ777U6YTyatP3P1wi3xw",
                title: "NEVER TOO SMALL Official Playlist",
                description: "Explore space-saving marvels in the innovative designs of compact living environments.",
                vidCount: 150,
                channelId: "",
                channelTitle: "NEVER TOO SMALL",
                thumbnailURL: "https://i.ytimg.com/vi/bA6C7QvTqZQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKtmnlvwJBpZbWf1_XBuDYcmJG2w",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPu1g1VZ5_9vzfGYd9O6p_c0EK3N3Z8TrpRux12Hw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@nevertoosmall",
                firstVidId: null
            },
            {
                id: "UULPoc2ZM2cYas4DijNdaEJXUA",
                title: "Architectural Design",
                description: "A detailed insight into the design process of a skilled architect.",
                vidCount: 40,
                channelId: "",
                channelTitle: "30X40 Design Workshop",
                thumbnailURL: "https://i.ytimg.com/vi/ly8orBNiNQM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBMl-IO2s2XziXqmOneR8iVbNeJGg",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@30by40",
                firstVidId: null
            },
            {
                id: "PL999ZDYL8QbTqnT8PZshZzJa7tat-Vdcj",
                title: "Tiny House Tours",
                description: "Experience unique tiny homes worldwide, celebrating sustainable living and creative design.",
                vidCount: 292,
                channelId: "",
                channelTitle: "Living Big In A Tiny House",
                thumbnailURL: "https://i.ytimg.com/vi/wAsXkkLumrk/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCE1YQe2sTpdeZbkAtTMnWtbaSLbw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM49fR69HbYoFhsWkmCsi7SwgDIfrZA3ayVzXM4cw=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@livingbig",
                firstVidId: null
            },
            {
                id: "PLVRtRwc2n-r6ToS9OapZq9OilGU3zqrbi",
                title: "Une Fille, Une Style",
                description: "Influenceuses, actrices, filles en vue et stylées invitent Vogue dans leur appartement pour évoquer leurs influences, inspirations mode et autres trouvailles vintage.",
                vidCount: 77,
                channelId: "",
                channelTitle: "Vogue France",
                thumbnailURL: "https://i.ytimg.com/vi/EwPiQD1w4uU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCL_IRH-w11yatDduLJsjeq_oIlDw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@VogueFrance",
                firstVidId: null
            },
            {
                id: "PLpi4YdMCC439_CyF_AcdIhHNZXGmejGtw",
                title: "Architects do Makeovers",
                description: "A close look at the design processes of accomplished architects and designers.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Architectural Digest",
                thumbnailURL: "https://i.ytimg.com/vi/f2HVUN0d4Jo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPsyOwZPkX6jMFfj-ku2f9DAK9ow",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@Archdigest",
                firstVidId: null
            }
        ]
    },
    {
        title: "Arts",
        playlists: [
            {
                id: "PLpEqmyo6EfvLFKVCc1RzCoUGfGMqJV_Kg",
                title: "Art of Craft",
                description: "Find inspiration from artist profiles & demonstrations of their craft.",
                vidCount: 23,
                channelId: "",
                channelTitle: "Different Authors",
                thumbnailURL: "https://i.ytimg.com/vi/vcoRoP3Abt8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBR8SjK-LpyqF8EP5mYNTOpUumqWg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71T_faAoGOjTff65G4yZR3Mg",
                title: "The Beauty of Films",
                description: "Experience the magic of cinema with this playlist brimming with stunning imagery, accompanies by amazing soundtracks.",
                vidCount: 40,
                channelId: "",
                channelTitle: "Different Authors",
                thumbnailURL: "https://i.ytimg.com/vi/-FGVJS3rT80/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLABS_5dT0OZkhI1BCBLyNCS2GNVyg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvLBfTZweZnGN_QTosoWO_2i",
                title: "Sketchbook Tours",
                description: "Step inside the personal sketchbooks of some extraordinary artists.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Multiple Artists",
                thumbnailURL: "https://i.ytimg.com/vi/OmLkBQmZQM8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAAm1MJt-sbBgIwMGQIpbQlzVWBrQ",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "UULPePDFpCr78_qmVtpoB1Axaw",
                title: "Great Art Explained",
                description: "Deciphering some of history's greatest artworks, from \"The Starry Night\" to \"Nighthawks.\"",
                vidCount: 32,
                channelId: "",
                channelTitle: "Great Art Explained",
                thumbnailURL: "https://i.ytimg.com/vi/IBcB_dYtGUg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDLsrhuZlz8kzcOwffTFXF6pchw4g",
                channelImgSrc: "https://yt3.ggpht.com/SVoD_4bbVOt1Nc3ncoDbMq7s-LU87TWovuFlUw3O0wQAKik0lwMwccnCWcp65cHSnZ4SQbuDPCc=s88-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BaumgartnerRestoration",
                firstVidId: null
            },
            {
                id: "PLOBH6dux3B0gLfU6SK7IdWeCZMa49H___",
                title: "Art Book Reviews",
                description: "Insightful critiques and explorations of the artworks from amazing films & video games.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Adam Duff LUCIDPIXUL",
                thumbnailURL: "https://i.ytimg.com/vi/hXkbS8A-qo0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAdpEaRG44I1gqG4xAWmf1A0FKLDg",
                channelImgSrc: "https://yt3.googleusercontent.com/stXTo4OSGjHAwwQ7zwRH8xHF24_jBFmfnyJEn7a9YUBeS_k9xTwdka8J15mL5MFfQ85naI0O6A=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@AdamDuffArt",
                firstVidId: null

            },
            {
                id: "PLFB0oFTSWSYb1mpL9YCFAT1YmSl3G--Ew",
                title: "3D Render Montages",
                description: "Get inspired by the works of hundreds of digital artists from pwnisher's 3D render challenges.",
                vidCount: 10,
                channelId: "",
                channelTitle: "pwnisher",
                thumbnailURL: "https://i.ytimg.com/vi/EdCvwmebWN0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLArWq2ck_Aub2tg0mWSR1yc4E4rhQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ER3I3TTJPZ6s7F0ARY1a88touU80pbINHVK8iYD45HC-TgEmcpcQJqVAVNxC4jxjcIGTQ1fe=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@pwnisher",
                firstVidId: null
            },
            {
                id: "PL5JqSuIvtmAMFmxJcr-v-9iTl4RY6nN5s",
                title: "Art History",
                description: "Learn about the centuries of art history from the Renaissance to 19th Century Romanticism.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Perspective",
                thumbnailURL: "https://i.ytimg.com/vi/XA_CqvjQWu8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAv-wC4b_dVCFJhYfDakd-7eEdkmA",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@PerspectiveArts",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvIlazR90JTrBOEMi44x-5Ct",
                title: "LOTR Appendices",
                description: "LOTR’s creative brilliance in filmmaking, fashion, music & more is displayed in this amazing BTS look at the making of some of the best films ever made.",
                vidCount: 9,
                channelId: "",
                channelTitle: "Everything In Middle Earth",
                thumbnailURL: "https://i.ytimg.com/vi/MY8i0E7TdWs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAmAvI2HUoic0Y_fSA1JX90HI9QZQ",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@EverythingInMiddleEarth",
                firstVidId: null

            },
            {
                id: "PLpEqmyo6EfvIUMb4z97ohT4GGyy14FDsa",
                title: "Great Big Story - Art Stories",
                description: "Explore the stories of artist around the world for boundless inspiration.",
                vidCount: 27,
                channelId: "",
                channelTitle: "Great Big Story",
                thumbnailURL: "https://i.ytimg.com/vi/xMgz61YjoLU/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCjRWtbDgt0GV4CDjRjVgW5NsynEQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ek2CK7M2HU9SCi7SkN10_1BfP7HpEjXA7lieUdPgamKJYhyJbLezmsj7rF3t6KtTOZl0Zrq1IQ=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@GreatBigStory",
                firstVidId: null
            },
            {
                id: "UULPNNOvB507MRfny7Jcv8MmOw",
                title: "Sam Does Art",
                description: "Reactions and helpful tips from the one the internet's most popular digital artists.",
                vidCount: 36,
                channelId: "",
                channelTitle: "Sam Does Arts",
                thumbnailURL: "https://i.ytimg.com/vi/wZxc71tUz8s/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVO8isTqAgkELDBZAsTJVV_cZiug",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqM5ZbMDBn9PJevUnYNm-7cNzr44NPGOOXgI8Hct=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@samdoesarts",
                firstVidId: null

            },
        ]
    },
    {
        title: "History",
        playlists: [
            {
                id: "PLTlW3nrfe71SKOxD3-wQXFeBis96X49RU",
                title: "Hellenic Cultures",
                description: "An odyssey through Greek cultures, from the Spartans to the Macedonians.",
                vidCount: 14,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/6eMKOoZdvJo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDTQAOBxMLn7sozyz8JDgrCaPslzg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QKHBQDJQToNoDFalofe7n5",
                title: "Asiatic and Middle Eastern",
                description: "History stretching from the Persians and the Abassids to the Chinese dynasties and Feudal Japan.",
                vidCount: 13,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/ZnRX_Cqhwb8/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPL37UVlwOZ_HiVzq5JKB6AMgsQg",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71RxHW8F2phUtDAxJsKQxsaP",
                title: "Rome",
                description: "Travel back to the time when togas and imperical conquest were all the rage.",
                vidCount: 23,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/CU2AOz8sav4/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAl9frJrxtNp4plAzkcENOoxwSN0Q",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLUOc2qodFHp-mOphKW9RzQLsFTt-IV9RY",
                title: "Napoleonic Wars",
                description: "Delve into campaigns that bore an empire spear-headed by one of history's greatest military figures.",
                vidCount: 28,
                channelId: "",
                channelTitle: "Epic History TV",
                thumbnailURL: "https://i.ytimg.com/vi/nDZGL1xsqzs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBVtD39mdAG0acFwDBvd2fyWsl4nQ",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71QnPQOPKt8cvY3U05BPx7zs",
                title: "Ancient Egypt",
                description: "Unearth the mysteries and wonders of Ancient Egypt's rich history.",
                vidCount: 12,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/ZrJe2Ab2t0Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB9leLyG_Eh9mJUdoUVUzevBjAk8g",
                channelImgSrc: "",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLq0ER3EMJsCFXxap9t3JNbq1dX-49z16o",
                title: "Legends And Mysteries",
                description: "Delve into the beguiling mysteries and myths of the ancient world.",
                vidCount: 11,
                channelId: "",
                channelTitle: "Odyssey - Ancient History Documentaries",
                thumbnailURL: "https://i.ytimg.com/vi/ysnzl5fdtMI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCCUlrUFU16ddFC8hIrXWtG5lMyaw",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@odyssey",
                firstVidId: null
            },
            {
                id: "PLTlW3nrfe71TD1rvpmiCa13A0jImzJkbQ",
                title: "Prehistory",
                description: "Explore the roots human ancestry and the animals they lived with from the Stone Age to Bronze Age.",
                vidCount: 17,
                channelId: "",
                channelTitle: "Multiple Authors",
                thumbnailURL: "https://i.ytimg.com/vi/vJybfmbrOCE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBH-W80DpEAvzmwOE6BVlThyFB3Zg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqMY-f7U8KIKTOUo2EhmndX9FtWmQBTjXAgN3fY1=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "",
                firstVidId: null
            },
            {
                id: "PLq0ER3EMJsCEbrCW0lE3COXpQrw3791qH",
                title: "Timeline's Ancient Civilisations",
                description: "Step back in time to the glory days of Ancient Rome.",
                vidCount: 19,
                channelId: "",
                channelTitle: "Timeline - World History Documentaries",
                thumbnailURL: "https://i.ytimg.com/vi/RCI28U2TvVs/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBZPnHpRxmjEtoYH2f1QJfKT2EoVQ",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqPjQK0xKlyZpbWUMzcE5BcJHvArxeKNCki2ijo1Pg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@TimelineChannel",
                firstVidId: null
            },
            {
                id: "PLUOc2qodFHp8mvnBE_Ya6Bj0HYnRo4XiY",
                title: "Epic History TV",
                description: "Dramatic, fast-moving, fact-packed history videos to help you make sense of epic events that have shaped the modern world.",
                vidCount: 93,
                channelId: "",
                channelTitle: "Epic History TV",
                thumbnailURL: "https://i.ytimg.com/vi/K7lb6KWBanI/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAg7bIfY5tljmHe_WHysOttvs__MQ",
                channelImgSrc: "https://yt3.googleusercontent.com/8v0oV3cbOYcwrieYDY4sLLgRXMBdpE5VZ_vDgMia1LGObLEaOfhLi8mHv-ip4BHI7Nhq3r6R2cg=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@EpichistoryTv",
                firstVidId: null
            },
            {
                id: "PLOjUdznmpOjjsJxgmAzwjdsoDomZjGYmc",
                title: "Medieval Battles",
                description: "Witness the epic clashes between armies of historic battles from antiquity.",
                vidCount: 28,
                channelId: "",
                channelTitle: "Baz Battles",
                thumbnailURL: "https://i.ytimg.com/vi/BV5Z_CHbkAw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCC12FXPNGVlK33rDIU0vniXLX0fg",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                firstVidId: null
            },
            {
                id: "PLOjUdznmpOjiJQD_rOpw4iX8Vj-AoxGUe",
                title: "ASOIF History",
                description: "Battles from George R.R. Martin's widely beloved ASOIF universe.",
                vidCount: 5,
                channelId: "",
                channelTitle: "Baz Battles",
                thumbnailURL: "https://i.ytimg.com/vi/k1zsvHusfPQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBswM110Dk6U6XWHlztR2bQt6B70w",
                channelImgSrc: "https://yt3.googleusercontent.com/ytc/AGIKgqOBN9fKdQuOjx3MuuXj5bDXNTcdb3V0Qv4PGpBD=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@BazBattles",
                firstVidId: null
            },
        ]
    },
    {
        title: "Culture",
        playlists: [
            {
                id: "PLW1Mwtj8qAjmvVnVEbBhbcBOAFWlj8mOs",
                title: "Regional Eats",
                description: "We travel to a food's area of origin to see how it's made, find out its history.",
                vidCount: 82,
                channelId: "",
                channelTitle: "Insider Food",
                thumbnailURL: "https://i.ytimg.com/vi/ZyZh_FIhGlU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAwFZ0JRuVsIJ-rl4mYJFNUY-HI8g",
                channelImgSrc: "https://yt3.googleusercontent.com/my5fZEjea_-N5p8mhqrdNIxghb-KjP9AcH4lQlYzNrRlwzjx3Gbay0JlOCZqJOcp_sTjF3rmBV8=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@InsiderFood",
                firstVidId: null
            },
            {
                id: "PLnPDn1Lb79JFjhC17KjxiFU41SKivZfrW",
                title: "Street Food Icons",
                description: "Discover the legendary founders of famous street-food eateries all over the world.",
                vidCount: 82,
                channelId: "",
                channelTitle: "Munchies",
                thumbnailURL: "https://i.ytimg.com/vi/Fpny0WP8sYw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByNtcd0gC-usJeeaAvmRfi_oB7mQ",
                channelImgSrc: "https://yt3.googleusercontent.com/JU6HzojvmJwDKybljkQc83LESYZG7NmdPgPo2xXoeHUcUmR98tHjIUhIekgMFGaRyEDgzuv-AA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@Munchies",
                firstVidId: null
            },
            {
                id: "PLcpuu5BzmasC7cI-B713EY3xdpWrLhDdH",
                title: "Japan Day in the Life Series by Paolo from TOKYO",
                description: "Paolo's 'Day-in-the-life' series provides an unmatched, intimate peek into modern day Japanese life.",
                vidCount: 39,
                channelId: "",
                channelTitle: "Paolo from TOKYO",
                thumbnailURL: "https://i.ytimg.com/vi/B5pKw6flFZE/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAghIXJ5n9TxupLK1lpkmDfcKvLCw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@PaolofromTOKYO",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvJEd06jNTuUSr9Z3ITXhjbT",
                title: "Vogue Street Style",
                description: "From the streets of Conpenhagen and Paris to Tokyo and Milan, get inspired by fits of fashion enthusiasts around the world.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Vogue",
                thumbnailURL: "https://i.ytimg.com/vi/zPys5ZYL-ng/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLByf0Jsm8dNJ21M7nX2IkaPPVIMTw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@Vogue",
                firstVidId: null
            },
            {
                id: "UULFcAd5Np7fO8SeejB1FVKcYw",
                title: "Best Ever Food Review Show",
                description: "Sonny's culinary journeys around the world offers some of the most entertaining and enriching food content available.",
                vidCount: 700,
                channelId: "",
                channelTitle: "Best Ever Food Review Show",
                thumbnailURL: "https://i.ytimg.com/vi/a5yP1yqGEMo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBYc1gfrW0rEMDlyfIldjr9TDL3OQ",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@BestEverFoodReviewShow",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKXJDoVj2k3Xo6wcZM7qgXt",
                title: "THR Roundtables",
                description: "Candid conversations with titans of the film industry.",
                vidCount: 20,
                channelId: "",
                channelTitle: "The Hollywood Reporter",
                thumbnailURL: "https://i.ytimg.com/vi/hJH2EyvvEBA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAjkFRfVJjH-DS2rBdGRA1TrU7UcQ",
                channelImgSrc: "https://yt3.googleusercontent.com/7FPGaZ3f81d6IXj-eZwD5_f8UhKNFTMg6jvesjs42nnEwTKrFGnIBGqxbP0QZs2MyAKF2zQHmFA=s176-c-k-c0x00ffffff-no-rj",
                channelURL: "https://www.youtube.com/@hollywoodreporter",
                firstVidId: null
            }
        ]
    },
    {
        title: "News & Politics",
        playlists: [
            {
                id: "PLw613M86o5o7q1cjb26MfCgdxJtshvRZ-",
                title: "Vice News",
                description: "Stay informed and up-to-date with news that capture the people at the heart of stories, and focus on the ideas, issues, and context that moss outlets miss.",
                vidCount:  1000,
                channelId: "",
                channelTitle: "Vice News",
                thumbnailURL: "https://i.ytimg.com/vi/d-Dkm_-1uaY/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCuwVd_2l4sNvkgnxRmtp2eu7ps6g",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@VICENews",
                firstVidId: null
            },
            {
                id: "UULFsD-Qms-AkXDrsU962OicLw",
                title: "The New Yorker | Latest",
                description: "The New Yorker delivers reporting and commentary on politics, foreign affairs, business, technology, culture, arts, humor, fiction, poetry, and cartoons.",
                vidCount:  1000,
                channelId: "",
                channelTitle: "New Yorker",
                thumbnailURL: "https://i.ytimg.com/vi/h-hJYtfsNB0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBAVwFcXbpQ0luaEJuNR8diDhGc5g",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@newyorker",
                firstVidId: null
            },
            {
                id: "PL4CGYNsoW2iBfrlL3yvnqQqCMdiBQol1D",
                title: "Latest News | The New York Times",
                description: "The New York Times is the most powerful engine for independent, boots-on-the-ground and deeply reported journalism.",
                vidCount:  1000,
                channelId: "",
                channelTitle: "The New York Times",
                thumbnailURL: "https://i.ytimg.com/vi/SE_S-dY5ZHM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLD2OeE1aO03LezOdUnozGjne47F3w",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@nytimes",
                firstVidId: null
            },
            {
                id: "PLpEqmyo6EfvKcNODQCgDNAO5o09yXvJD-",
                title: "Best of Vice News",
                description: "Our favorite pieces of journalism from Vice News.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Vice News",
                thumbnailURL: "https://i.ytimg.com/vi/iIFi_Rgm-T8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAWPRdAGdU3LNv__jDWjXvRNYEASw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@VICENews",
                firstVidId: null
            },
            {
                id: "PLMFGVXWuJ1C7Bcu6apMqmP3B0yL0BeJRe",
                title: "Great Big Picture",
                description: "Delivering unique and enriching stories about people from around the global that often overlooked by mainstream media.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Great Big Story",
                thumbnailURL: "https://i.ytimg.com/vi/t-vMC5a9I0Y/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLB5n7w9khkh-SrnHNkza_swIkoXBw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@GreatBigStory",
                firstVidId: null
            },
            {
                id: "PLzGHKb8i9vTztD1EkX_S0V0Agv8IUDP-C",
                title: "Al Jazeera Breaking News",
                description: "Real-time updates on the latest headlines.",
                vidCount: 16,
                channelId: "",
                channelTitle: "Al Jazeera English",
                thumbnailURL: "https://i.ytimg.com/vi/KBsSuW2c1pQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBqnIdXyHOZtF1mj0xrV0c9jhT_Sw",
                channelImgSrc: "",
                channelURL: "https://www.youtube.com/@aljazeeraenglish",
                firstVidId: null
            },
        ]
    }
]

export default YT_PLAYLIST_GROUPS