export const defaultThemes: DefaultTheme[] = [
    {
        title: "Dark Mode",
        thumbnailImgSrc: "/dark-mode-icon.png",
        sectionDetails: { title: "default", index: 0 },
        twinTheme: { sectionName: "default", index: 1 },
        styling: {
            isDark: true,
            hasTwin: true,
            isHeaderElementTextLight: false,
            primaryBgColor: "#0C0B0C",
            secondaryBgColor: "#0F0E0F",
            tertiaryBgColor: "#181718",
            fgColor1: "163, 182, 255",
            fgColor2: "163, 182, 255",
            textColor1: "255, 255, 255",
            textColor2: "255, 255, 255",
            hoverColor: "#111112",
            hoverColor2: "#151516",
            hoverColor3: "#121213",
            tabColor: "#181819",
            tabHighlightColor: "#FFFFFF",
            tabHighlightBoxShadow: "0px -1px 11px rgba(255, 255, 255, 0.21)",
            modalBgColor: "#0B0B0B",
            modalBgAccentColor: "#131214",
            muiscPlayerBgColor: "rgba(50, 50, 50, 0.45)",
            musicProgressFgColor: "",
            navMenuBgColor: "#110F11",
            headerElementBgColor: "#161516",
            headerElementTextColor: "255, 255, 255",
            headerElementBorderVal: "0.6px solid rgba(55, 55, 55, 0.28)",
            headerTimeColor: "#FFFFFF",
            headerProgressColor1: "#FFFFFF",
            headerProgressColor2: "#676767",
            headerTrackColor2: "#5C5C5C",
            headerTrackColor1: "#393939",
            baseProgressColor1: "#E7E7E7",
            baseProgressColor2: "#7D7D7D",
            baseTrackColor1: "#232323",
            baseTrackColor2: "#373737",
            progressBallGlow: "0px 0px 9px 2px rgba(255, 255, 255, 0.18)",
            navIconColor: "none",
            navIconBgColor: "#1A171A",
            sessionBgColor: "#1C1C1C",
            sessionBorderVal: "0.4px solid #262626",
            sessionShadowVal: "none",
            bentoBoxBgColor: "#0e0e0f",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            themeToggleBtnBgColor: "#151315",
            iconToggleBtnBgColor: "#252325",
            highlighterToggleBtnBgColor: "#1A181A",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#111011",
            midPanelAccentColor1: "#171517",
            midPanelAccentColor2: "#101011",
            midPanelAccentColor3: "#141417",
            midPanelAccentTextColor: "white",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            dropdownMenuBgColor1: "#141314",
            dropdownMenuBgHoverColor1: "#171617",
            dropdownMenuBgColor2: "#141314",
            dropdownMenuBgHoverColor2: "#171717",
        }
    } as DefaultTheme,
    {
        title: "Light Mode",
        thumbnailImgSrc: "/light-mode-icon.png",
        sectionDetails: { title: "default", index: 1 },
        twinTheme: { sectionName: "default", index: 0 },
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FFFEFF",
            secondaryBgColor: "#FFFCF6",
            tertiaryBgColor: "#FAF8F2",
            fgColor1: "163, 182, 255",
            fgColor2: "163, 182, 255",
            sessionBgColor: "#CEC4B0",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#FBFBFB",
            hoverColor2: "#F9F9F9",
            hoverColor3: "#ffffff",
            tabColor: "#F6F6F6",
            tabHighlightColor: "#A3C2FF",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#A3B6FF",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            headerElementShadow: "none",
            headerTimeColor: "#9EA0A7",
            headerProgressColor1: "",
            headerProgressColor2: "",
            headerTrackColor2: "",
            headerTrackColor1: "",
            baseProgressColor1: "",
            baseProgressColor2: "",
            baseTrackColor1: "",
            baseTrackColor2: "",
            progressBallGlow: "none",
            modalBgColor: "#FBFBFB",
            modalBgAccentColor: "#f5f5f5",
            bentoBoxBgColor: "#FFFFFF",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 7px 0px rgba(0, 0, 0, 0.05)",
            muiscPlayerBgColor: "#A3B6FF",
            musicProgressFgColor: "",
            navMenuBgColor: "#FDFDFD",
            navIconColor: "#d1c29e",
            navIconBgColor: "none",
            themeToggleBtnBgColor: "#F3F3F3",
            iconToggleBtnBgColor: "#E3E3E3",
            highlighterToggleBtnBgColor: "#FAFAFA",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#F9F9F9",
            midPanelAccentColor1: "#EDEDED",
            midPanelAccentColor2: "227, 227, 227",
            midPanelAccentColor3: "223, 227, 227",
            midPanelAccentTextColor: "89, 89, 89",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 4px 12px 0px rgba(56, 56, 56, 0.1)",
            dropdownMenuBgColor1: "#ffffff",
            dropdownMenuBgHoverColor1: "#ffffff",
            dropdownMenuBgColor2: "0px 4px 12px 0px rgba(56, 56, 56, 0.1)",
            dropdownMenuBgHoverColor2: "#ffffff",
        }
    } as DefaultTheme
]
export const darkColorThemes: ColorTheme[] = [
    {
        title: "Midnights",
        sectionDetails: { title: "dark", index: 0 },
        twinTheme: { sectionName: "light", index: 11 },
        colorPalette: ["#141113", "#2D252A", "#DBB590", "#F8E1CC", "#FFF5EC"],
        styling: {
            isDark: true,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#120e11",
            secondaryBgColor: "#161013",
            tertiaryBgColor: "#F4F0E6",
            fgColor1: "228, 188, 150",
            fgColor2: "228, 188, 150",
            sessionBgColor: "#FAF6ED",
            sessionBorderVal: "0.4px solid rgba(164, 164, 164, 0.26)",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "251, 245, 240",
            textColor2: "30, 30, 30",
            hoverColor: "#141013",
            hoverColor2: "#151114",
            hoverColor3: "#191618",
            tabColor: "#1a1619",
            tabHighlightColor: "#eed5b2",
            tabHighlightBoxShadow: "0px 0px 12px 1px rgba(228, 188, 150, 0.18)",
            headerElementBgColor: "#171315",
            headerElementBorderVal: "0.6px solid rgba(55, 55, 55, 0.28)",
            headerElementTextColor: "237, 210, 185",
            headerElementShadow: "none",
            headerTimeColor: "#E4C096",
            headerProgressColor1: "#FDE6D0",
            headerProgressColor2: "#73655C",
            headerTrackColor1: "#2d292a",
            headerTrackColor2: "#3B3839",
            baseProgressColor1: "#FDE6D0",
            baseProgressColor2: "#73655C",
            baseTrackColor1: "#211D1E",
            baseTrackColor2: "#3F3D3C",
            progressBallGlow: "0px 0px 9px 2px rgba(255, 255, 255, 0.1)",
            modalBgColor: "#0c0a0c",
            modalBgAccentColor: "#100D0F",
            bentoBoxBgColor: "#110e10",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            muiscPlayerBgColor: "rgba(32, 28, 31, 0.43)",
            musicProgressFgColor: "",
            navMenuBgColor: "#171114",
            navIconColor: "#E4B496",
            navIconBgColor: "#1c1619",
            themeToggleBtnBgColor: "#130E11",
            iconToggleBtnBgColor: "#1D171B",
            highlighterToggleBtnBgColor: "#191517",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#171315",
            midPanelAccentColor1: "#1c1619",
            midPanelAccentColor2: "#171114",
            midPanelAccentColor3: "#1a1417",
            midPanelAccentTextColor: "white",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            dropdownMenuBgColor1: "#131012",
            dropdownMenuBgHoverColor1: "#171415",
            dropdownMenuBgColor2: "#151114",
            dropdownMenuBgHoverColor2: "#1a1519",
        }
    },
    {
        title: "Dark Academia",
        sectionDetails: { title: "dark", index: 1 },
        twinTheme: { sectionName: "light", index: 8 },
        colorPalette: [ "#241D15", "#8D775E", "#564E40", "#B9AE99", "#B8A086" ],
        styling: {
            isDark: true,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#121110",
            secondaryBgColor: "#141312",
            tertiaryBgColor: "#F4F0E6",
            fgColor1: "86, 78, 64",
            fgColor2: "148, 113, 93",
            sessionBgColor: "#FAF6ED",
            sessionBorderVal: "0.4px solid rgba(164, 164, 164, 0.26)",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "246, 233, 224",
            textColor2: "30, 30, 30",
            hoverColor: "#141211",
            hoverColor2: "#191716",
            hoverColor3: "#191618",
            tabColor: "#171514",
            tabHighlightColor: "#725644",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#1A1816",
            headerElementBorderVal: "none",
            headerElementTextColor: "244, 239, 235",
            headerElementShadow: "none",
            headerTimeColor: "#726359",
            headerProgressColor1: "#6B604E",
            headerProgressColor2: "#34312E",
            headerTrackColor1: "#282625",
            headerTrackColor2: "#4B4948",
            baseProgressColor1: "#6B604E",
            baseProgressColor2: "#34312E",
            baseTrackColor1: "#1E1C1C",
            baseTrackColor2: "#3F3D3C",
            progressBallGlow: "none",
            modalBgColor: "#0C0B0A",
            modalBgAccentColor: "#100f0e",
            bentoBoxBgColor: "#100F0E",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            muiscPlayerBgColor: "rgba(42, 36, 31, 0.19)",
            musicProgressFgColor: "#C6B8AB",
            navMenuBgColor: "#141312",
            navIconColor: "#94715D",
            navIconBgColor: "#191715",
            themeToggleBtnBgColor: "#11100f",
            iconToggleBtnBgColor: "#191816",
            highlighterToggleBtnBgColor: "#181716",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#161514",
            midPanelAccentColor1: "#1c1916",
            midPanelAccentColor2: "#161514",
            midPanelAccentColor3: "#191714",
            midPanelAccentTextColor: "white",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            dropdownMenuBgColor1: "#191817",
            dropdownMenuBgHoverColor1: "#161514",
            dropdownMenuBgColor2: "#161513",
            dropdownMenuBgHoverColor2: "#191817",
        }
    },
    /* {
        title: "Dusk",
        sectionDetails: { title: "dark", index: 2 },
        twinTheme: { sectionName: "light", index: 7 },
        colorPalette: [ "#1A191A", "#232225", "#9792CD", "#B5A7F0", "#C8B8F3" ],
        styling: {
            isDark: true,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#0D0C0D",
            secondaryBgColor: "#111012",
            tertiaryBgColor: "#F4F0E6",
            fgColor1: "175, 159, 217",
            fgColor2: "238, 214, 172",
            sessionBgColor: "#FAF6ED",
            sessionBorderVal: "0.4px solid rgba(164, 164, 164, 0.26)",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "255, 255, 255",
            textColor2: "30, 30, 30",
            hoverColor: "#131113",
            hoverColor2: "#131113",
            hoverColor3: "#191618",
            tabColor: "#161416",
            tabHighlightColor: "#B4A4F8",
            tabHighlightBoxShadow: "0px 0px 12px 1px rgba(180, 164, 248, 0.15)",
            headerElementBgColor: "linear-gradient(90deg, #B3A1DA 18.15%, #B7A3DB 34.32%, #C4AADD 89.74%)",
            headerElementBorderVal: "none",
            headerElementTextColor: "255, 255, 255",
            headerElementShadow: "none",
            headerTimeColor: "#ECE3CC",
            headerProgressColor1: "#FFFFFF",
            headerProgressColor2: "#9282A6",
            headerTrackColor1: "#D6C6E9",
            headerTrackColor2: "#937EAD",
            baseProgressColor1: "#AF9FD9",
            baseProgressColor2: "#534C64",
            baseTrackColor1: "#3E3C3C",
            baseTrackColor2: "#1C191A",
            progressBallGlow: "none",
            modalBgColor: "#0B0A0B",
            modalBgAccentColor: "#070607",
            bentoBoxBgColor: "#0F0E0F",
            bentoBoxBorder: "none",
            bentoBoxShadow: "none",
            muiscPlayerBgColor: "rgba(29, 26, 30, 0.19)",
            musicProgressFgColor: "#C6B8AB",
            navMenuBgColor: "#100E10",
            navIconColor: "#AF9FD9",
            navIconBgColor: "#171417",
            themeToggleBtnBgColor: "#0e0c0e",
            iconToggleBtnBgColor: "#1D1B1D",
            highlighterToggleBtnBgColor: "#121012",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#171417",
            midPanelAccentColor1: "#171417",
            midPanelAccentColor2: "#110f11",
            midPanelAccentColor3: "#161316",
            midPanelAccentTextColor: "white",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            dropdownMenuBgColor1: "#141314",
            dropdownMenuBgHoverColor1: "#141314",
            dropdownMenuBgColor2: "",
            dropdownMenuBgHoverColor2: "#141314",
        }
    } */
]
export const lightColorThemes: ColorTheme[] = [
    {
        title: "Olive",
        sectionDetails: { title: "light", index: 0 },
        colorPalette: [
            "#72673A", "#A2956E", "#BFB38D", "#D2C7A8", "#DBD5C1"
        ],
        twinTheme: null,
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#ECE7D6",
            secondaryBgColor: "#F0ECDF",
            tertiaryBgColor: "#F4F0E6",
            fgColor1: "160, 148, 113",
            fgColor2: "160, 148, 113",
            sessionBgColor: "#FAF6ED",
            sessionBorderVal: "0.4px solid rgba(164, 164, 164, 0.26)",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F7F2E2",
            hoverColor2: "#f2eee0",
            hoverColor3: "#ffffff",
            tabColor: "#efeadc",
            tabHighlightColor: "#A39673",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#E6E1D2",
            headerElementBorderVal: "none",
            headerElementTextColor: "132, 126, 108",
            headerElementShadow: "none",
            headerTimeColor: "#958B6E",
            headerProgressColor1: "#807965",
            headerProgressColor2: "#A39B85",
            headerTrackColor1: "#BEB9AC",
            headerTrackColor2: "#918A79",
            baseProgressColor1: "#908870",
            baseProgressColor2: "#C4BCA4",
            baseTrackColor1: "#CEC6B0",
            baseTrackColor2: "#ABA38B",
            progressBallGlow: "none",
            modalBgColor: "#F5F0DF",
            modalBgAccentColor: "#EFEBDD",
            bentoBoxBgColor: "#FBF7E9",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#A09471",
            musicProgressFgColor: "",
            navMenuBgColor: "#F0ECDF",
            navIconColor: "#A2956E",
            navIconBgColor: "#ece7d9",
            themeToggleBtnBgColor: "ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "none",
            midPanelShadow: "0px 5px 8px 0px rgba(0, 0, 0, 0.04)",            
            midPanelBaseColor: "#F0ECDF",
            midPanelAccentColor1: "#F1EDE0",
            midPanelAccentColor2: "#E6E1D2",
            midPanelAccentColor3: "#e6e1d2",
            midPanelAccentTextColor: "67, 63, 50",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 4px 18px 0px rgba(123, 123, 123, 0.07)",
            dropdownMenuBgColor1: "#FBF7E9",
            dropdownMenuBgHoverColor1: "#F4F0E3",
            dropdownMenuBgColor2: "#f4f0e1",
            dropdownMenuBgHoverColor2: "#EDE9DB",
        }
    },
    {
        title: "Basil",
        sectionDetails: { title: "light", index: 1 },
        twinTheme: null,
        colorPalette: ["#66754C", "#8E9B6D", "#A5AB95", "#D5C7AA", "#FAF5EB"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#fef9f0",
            secondaryBgColor: "#FFFCF6",
            tertiaryBgColor: "#FAF8F2",
            fgColor1: "156, 160, 140",
            fgColor2: "206, 196, 176",
            sessionBgColor: "#CEC4B0",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#FAF7F1",
            hoverColor2: "#FAF5ED",
            hoverColor3: "#ffffff",
            tabColor: "#f4efe6",
            tabHighlightColor: "#d2c4a9",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#F6F2E8",
            headerElementBorderVal: "border: 0.6px solid #E4E4E4",
            headerElementTextColor: "139, 132, 110",
            headerElementShadow: "none",
            headerTimeColor: "#c3af89",
            headerProgressColor1: "#CEC4B0",
            headerProgressColor2: "#807867",
            headerTrackColor1: "#E2DCCE",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#CEC4B0",
            baseProgressColor2: "#8E7E5E",
            baseTrackColor1: "#ECE7D5",
            baseTrackColor2: "#C2BAA4",
            progressBallGlow: "none",
            modalBgColor: "#FEF9F0",
            modalBgAccentColor: "#F3EFE7",
            bentoBoxBgColor: "#FFFCF6",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#CEC4B0",
            musicProgressFgColor: "",
            navMenuBgColor: "#FEF9F0",
            navIconColor: "#9CA08C",
            navIconBgColor: "#F9F3E9",
            themeToggleBtnBgColor: "ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "0.5px solid #ececec",
            midPanelShadow: "0px 5px 8px 0px rgba(0, 0, 0, 0.03)",            
            midPanelBaseColor: "#F8F3E7",
            midPanelAccentColor1: "#F7F2E8",
            midPanelAccentColor2: "#EFEBE4",
            midPanelAccentColor3: "#f6f0e7",
            midPanelAccentTextColor: "104, 96, 82",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 4px 12px 0px rgba(56, 56, 56, 0.1)",
            dropdownMenuBgColor1: "#FFFCF6",
            dropdownMenuBgHoverColor1: "#F8F5EF",
            dropdownMenuBgColor2: "#fffbf2",
            dropdownMenuBgHoverColor2: "#F8F4EB",
        }
    },
    {
        title: "Azul",
        sectionDetails: { title: "light", index: 2 },
        twinTheme: null,
        colorPalette: ["#5E73AF", "#7487BF", "#98A3C4", "#C5CAD8", "#FAF5EB"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FAF5EB",
            secondaryBgColor: "#fcf9f2",
            tertiaryBgColor: "#faf9f4",
            fgColor1: "109, 120, 154",
            fgColor2: "211, 198, 175",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "49, 57, 38",
            textColor2: "255, 255, 255",
            hoverColor: "#F8F4ED",
            hoverColor2: "#F5F0E7",
            hoverColor3: "#fffefa",
            tabColor: "#ede9e0",
            tabHighlightColor: "#7885b3",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#FFFCF5",
            headerElementBorderVal: "none",
            headerElementTextColor: "112, 118, 137",
            headerElementShadow: "none",
            headerTimeColor: "#6E7792",
            headerProgressColor1: "#6E799B",
            headerProgressColor2: "#454D63",
            headerTrackColor1: "#E7E2D4",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#6E799B",
            baseProgressColor2: "#454D63",
            baseTrackColor1: "#E7E2D4",
            baseTrackColor2: "#C2BDB1",
            progressBallGlow: "none",
            modalBgColor: "#FAF5EB",
            modalBgAccentColor: "#F6F2EB",
            bentoBoxBgColor: "#FDFAF4",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#5f6b90",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FAF5EB",
            navIconColor: "#7882a0",
            navIconBgColor: "#f5efe2",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "0.5px solid #ececec",
            midPanelShadow: "none",            
            midPanelBaseColor: "#f5efe3",
            midPanelAccentColor1: "#F7F1E6",
            midPanelAccentColor2: "#EFE9DD",
            midPanelAccentColor3: "#f5eee1",
            midPanelAccentTextColor: "115, 108, 96",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 2px 16px 5px rgba(0, 0, 0, 0.05)",
            dropdownMenuBgColor1: "#f8f4ed",
            dropdownMenuBgHoverColor1: "#f2eee7",
            dropdownMenuBgColor2: "#fef9f0",
            dropdownMenuBgHoverColor2: "#F7F2E9"
        }
    },
    {
        title: "Vert",
        sectionDetails: { title: "light", index: 3 },
        twinTheme: null,
        colorPalette: ["#508D6C", "#739984", "#93B6A3", "#C1C9C0", "#FAF5EB"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FAF5EB",
            secondaryBgColor: "#fcf9f2",
            tertiaryBgColor: "#faf9f4",
            fgColor1: "105, 119, 105",
            fgColor2: "211, 198, 175",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "49, 57, 38",
            textColor2: "255, 255, 255",
            hoverColor: "#F8F4ED",
            hoverColor2: "#F5F0E7",
            hoverColor3: "#fffefa",
            tabColor: "#ede9e0",
            tabHighlightColor: "#839B90",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#FFFCF5",
            headerElementBorderVal: "none",
            headerElementTextColor: "104, 119, 112",
            headerElementShadow: "none",
            headerTimeColor: "#6D7F65",
            headerProgressColor1: "#697769",
            headerProgressColor2: "#2D322D",
            headerTrackColor1: "#E7E2D4",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#697769",
            baseProgressColor2: "#2D322D",
            baseTrackColor1: "#BCB5A0",
            baseTrackColor2: "#E4E0D2",
            progressBallGlow: "none",
            modalBgColor: "#FAF5EB",
            modalBgAccentColor: "#F3EFE7",
            bentoBoxBgColor: "#FDFAF4",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.03)",
            muiscPlayerBgColor: "#697769",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FAF5EB",
            navIconColor: "#828F82",
            navIconBgColor: "#f5efe2",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "0.5px solid #ececec",
            midPanelShadow: "none",            
            midPanelBaseColor: "#f5efe3",
            midPanelAccentColor1: "#F7F1E6",
            midPanelAccentColor2: "#EFE9DD",
            midPanelAccentColor3: "#f5eee1",
            midPanelAccentTextColor: "115, 108, 96",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 2px 16px 5px rgba(0, 0, 0, 0.05)",
            dropdownMenuBgColor1: "#f8f4ed",
            dropdownMenuBgHoverColor1: "#f2eee7",
            dropdownMenuBgColor2: "#fef9f0",
            dropdownMenuBgHoverColor2: "#F7F2E9"
        }
    },
    {
        title: "Earth",
        sectionDetails: { title: "light", index: 4 },
        twinTheme: null,
        colorPalette: ["#979687", "#C0BEA6", "#D0CCC2", "#E4BAA2", "#E9D3C5"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FAF5EB",
            secondaryBgColor: "#FDFAF4",
            tertiaryBgColor: "#FAF8F3",
            fgColor1: "156, 171, 183",
            fgColor2: "218, 198, 178",
            sessionBgColor: "#FEFBF4",
            sessionBorderVal: "0.4px solid #DEDCD7",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "60, 66, 85",
            textColor2: "255, 255, 255",
            hoverColor: "#F7F3ED",
            hoverColor2: "#F0EDE8",
            hoverColor3: "#ffffff",
            tabColor: "#ede9e0",
            tabHighlightColor: "#CFAB96",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#f3ede2",
            headerElementBorderVal: "none",
            headerElementTextColor: "139, 132, 110",
            headerElementShadow: "none",
            headerTimeColor: "#E6CB88",
            headerProgressColor1: "#C1BCAA",
            headerProgressColor2: "#918B76",
            headerTrackColor1: "#BEB9AC",
            headerTrackColor2: "#8A867C",
            baseProgressColor1: "#9CABB7",
            baseProgressColor2: "#637787",
            baseTrackColor1: "#E2DED1",
            baseTrackColor2: "#ADA9A0",
            progressBallGlow: "none",
            modalBgColor: "#FAF5EB",
            modalBgAccentColor: "#F3EFE7",
            bentoBoxBgColor: "#FDFAF4",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.03)",
            muiscPlayerBgColor: "#DAC6B2",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#C1BCAA",
            navIconColor: "#faf5eb",
            navIconBgColor: "#B9B5A5",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "none",
            midPanelShadow: "0px 3px 8px 0px rgba(0, 0, 0, 0.04)",            
            midPanelBaseColor: "#F3EEE2",
            midPanelAccentColor1: "#F5F0E5",
            midPanelAccentColor2: "#EBE6D7",
            midPanelAccentColor3: "#f3eee2",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            midPanelAccentTextColor: "114, 111, 100",
            dropdownMenuBgColor1: "#f8f4ed",
            dropdownMenuBgHoverColor1: "#f2eee7",
            dropdownMenuBgColor2: "#fef9f0",
            dropdownMenuBgHoverColor2: "#F7F2E9"
        }
    },
    {
        title: "Pearl",
        sectionDetails: { title: "light", index: 5 },
        twinTheme: null,
        colorPalette: ["#897D7D", "#A59B9B", "#D4C9C9", "#E4D8D8", "#FEFAF9"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FEFAF9",
            secondaryBgColor: "#FFFFFF",
            tertiaryBgColor: "#FFFFFE",
            fgColor1: "188, 161, 155",
            fgColor2: "195, 183, 183",
            sessionBgColor: "#DACDCD",
            sessionBorderVal: "0.4px solid rgba(132, 132, 132, 0.26)",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "52, 42, 42",
            textColor2: "255, 255, 255",
            hoverColor: "#FAF8F8",
            hoverColor2: "#F6F2F2",
            hoverColor3: "#ffffff",
            tabColor: "#f8f5f5",
            tabHighlightColor: "#beaeae",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#F4F0F0",
            headerElementBorderVal: "none",
            headerElementTextColor: "126, 113, 113",
            headerElementShadow: "none",
            headerTimeColor: "#C9B2B2",
            headerProgressColor1: "#A28989",
            headerProgressColor2: "#635454",
            headerTrackColor1: "#E1DED7",
            headerTrackColor2: "#9D9A94",
            baseProgressColor1: "#BAA2A2",
            baseProgressColor2: "#847373",
            baseTrackColor1: "#E6E4DF",
            baseTrackColor2: "#A19D92",
            progressBallGlow: "none",
            modalBgColor: "#FEFAF9",
            modalBgAccentColor: "#F6F3F2",
            bentoBoxBgColor: "#FFFFFF",
            bentoBoxBorder: "0.4px solid #EDEDED",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#c4b8b8",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FEFAF9",
            navIconColor: "#C2A9A9",
            navIconBgColor: "#F7F3F3",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#FFFEFE",
            midPanelAccentColor1: "#F4F0F0",
            midPanelAccentColor2: "#E8E8E8",
            midPanelAccentColor3: "#f7f3f2",
            midPanelAccentTextColor: "114, 101, 101",
            sidePanelBorder: "0.7px solid #E9E9E9",
            sidePanelShadow: "0px 2px 17px 7px rgba(0, 0, 0, 0.05)",
            dropdownMenuBgColor1: "#ffffff",
            dropdownMenuBgHoverColor1: "#F8F8F8",
            dropdownMenuBgColor2: "#ffffff",
            dropdownMenuBgHoverColor2: "#F8F8F8",
        }
    },
    {
        title: "Birch",
        sectionDetails: { title: "light", index: 6 },
        twinTheme: null,
        colorPalette: ["#878779", "#B0B1A1", "#B0A495", "#D4C9BB", "#FFFAF3"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FFF9F1",
            secondaryBgColor: "#FFFFFF",
            tertiaryBgColor: "#FFFFFE",
            fgColor1: "168, 169, 153",
            fgColor2: "168, 169, 153",
            sessionBgColor: "#DACDCD",
            sessionBorderVal: "0.4px solid rgba(132, 132, 132, 0.26)",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F5F3EF",
            hoverColor2: "#F3F1ED",
            hoverColor3: "#ffffff",
            tabColor: "#f3f1ed",
            tabHighlightColor: "#B0B1A1",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#f9f2eb",
            headerElementBorderVal: "none",
            headerElementTextColor: "139, 132, 110",
            headerElementShadow: "none",
            headerTimeColor: "#a6a09a",
            headerProgressColor1: "#A8A999",
            headerProgressColor2: "#6C6D61",
            headerTrackColor1: "#E2DCCE",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#A8A999",
            baseProgressColor2: "#6F7062",
            baseTrackColor1: "#E4E0D2",
            baseTrackColor2: "#BCB5A0",
            progressBallGlow: "none",
            modalBgColor: "#F7F2EB",
            modalBgAccentColor: "#F1EDE7",
            bentoBoxBgColor: "#FCFAF5",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#BDB1A3",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FFF9F2",
            navIconColor: "#A8A999",
            navIconBgColor: "#f9f2eb",
            themeToggleBtnBgColor: "#ECE7D8",
            iconToggleBtnBgColor: "#CAC3B0",
            highlighterToggleBtnBgColor: "#A09471",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#F6EFE7",
            midPanelAccentColor1: "#F6EFE7",
            midPanelAccentColor2: "#ede7e2",
            midPanelAccentColor3: "#f8f0e9",
            midPanelAccentTextColor: "100, 96, 93",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 3px 8px 1px rgba(0, 0, 0, 0.06)",
            dropdownMenuBgColor1: "#fffbf6",
            dropdownMenuBgHoverColor1: "#fbf7f2",
            dropdownMenuBgColor2: "#fffaf4",
            dropdownMenuBgHoverColor2: "#F8F3ED",
        }
    },
    {
        title: "Cactus",
        sectionDetails: { title: "light", index: 7 },
        twinTheme: null,
        colorPalette: ["#31342A", "#585E4A", "#D5AC9A", "#F1DEC2", "#FFFBF4"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FFFBF4",
            secondaryBgColor: "#FFFDF9",
            tertiaryBgColor: "#FCFAF6",
            fgColor1: "213, 172, 154",
            fgColor2: "125, 130, 114",
            sessionBgColor: "#FFFFFC",
            sessionBorderVal: "0.4px solid #E1E1E1",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.02)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#FBF8F2",
            hoverColor2: "#F8F6F0",
            hoverColor3: "#fffefa",
            tabColor: "#f4f0ed",
            tabHighlightColor: "#D5AC9A",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#F6F2E8",
            headerElementBorderVal: "none",
            headerElementShadow: "none",
            headerElementTextColor: "128, 131, 119",
            headerTimeColor: "#D5AC9A",
            headerProgressColor1: "#585E4A",
            headerProgressColor2: "#A5AB9A",
            headerTrackColor1: "#E2DCCE",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#585E4A",
            baseProgressColor2: "#979D8A",
            baseTrackColor1: "#E5DFCB",
            baseTrackColor2: "#BCB5A0",
            progressBallGlow: "none",
            modalBgColor: "#FBF6EF",
            modalBgAccentColor: "#F4F0EA",
            bentoBoxBgColor: "#FFFCF7",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#585E4A",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FFFCF5",
            navIconColor: "#D5AC9A",
            navIconBgColor: "#FBF6EF",
            themeToggleBtnBgColor: "#FBF6ED",
            iconToggleBtnBgColor: "#DFCFB7",
            highlighterToggleBtnBgColor: "#FBF6ED",
            midPanelBorder: "none",
            midPanelShadow: "0px 5px 8px 0px rgba(0, 0, 0, 0.04)",            
            midPanelBaseColor: "#fbf6ed",
            midPanelAccentColor1: "#FBF5ED",
            midPanelAccentColor2: "#F2EFEA",
            midPanelAccentColor3: "#f9f3eb",
            midPanelAccentTextColor: "83, 83, 83",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 3px 8px 1px rgba(0, 0, 0, 0.06)",
            dropdownMenuBgColor1: "#FFFBF4",
            dropdownMenuBgHoverColor1: "#F8F4ED",
            dropdownMenuBgColor2: "#fffbf5",
            dropdownMenuBgHoverColor2: "#F8F4ED",
        }
    },
    {
        title: "Stone",
        sectionDetails: { title: "light", index: 8 },
        twinTheme: { sectionName: "dark", index: 1 },
        colorPalette: ["#897B70", "#998A7B", "#B2A291", "#E2D9D2", "#FFF9EF"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FFF7E9",
            secondaryBgColor: "#FFFCF6",
            tertiaryBgColor: "#FAF8F2",
            fgColor1: "189, 177, 163",
            fgColor2: "189, 177, 163",
            sessionBgColor: "#CEC4B0",
            sessionBorderVal: "none",
            sessionShadowVal: "0px 2px 5px 0px rgba(0, 0, 0, 0.03)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F8F4EA",
            hoverColor2: "#F8F3E7",
            hoverColor3: "#fffefa",
            tabColor: "#f4efe6",
            tabHighlightColor: "#CEC4B0",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#f9f1e3",
            headerElementBorderVal: "none",
            headerElementTextColor: "139, 132, 110",
            headerElementShadow: "none",
            headerTimeColor: "#A88B75",
            headerProgressColor1: "#A79D95",
            headerProgressColor2: "#6C6762",
            headerTrackColor1: "#E2DCCE",
            headerTrackColor2: "#C2BDB1",
            baseProgressColor1: "#BDB1A3",
            baseProgressColor2: "#787169",
            baseTrackColor1: "#E4E0D2",
            baseTrackColor2: "#BCB5A0",
            progressBallGlow: "none",
            modalBgColor: "#FAF3E8",
            modalBgAccentColor: "#F3EDE5",
            bentoBoxBgColor: "#FFFAF1",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#BDB1A3",
            musicProgressFgColor: "",
            navMenuBgColor: "#FFF7E9",
            navIconColor: "#BEAD99",
            navIconBgColor: "#F8EFE0",
            themeToggleBtnBgColor: "#FAF1E0",
            iconToggleBtnBgColor: "#EDE3CF",
            highlighterToggleBtnBgColor: "#F2E9D8",
            midPanelBorder: "none",
            midPanelShadow: "0px 3px 10px 0px rgba(0, 0, 0, 0.085)",            
            midPanelBaseColor: "#F8F0E3",
            midPanelAccentColor1: "#F8F0E3",
            midPanelAccentColor2: "#F1E9DC",
            midPanelAccentColor3: "#f6efe1",
            midPanelAccentTextColor: "100, 97, 91",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 4px 17px 0px rgba(56, 56, 56, 0.08)",
            dropdownMenuBgColor1: "#fff9ef",
            dropdownMenuBgHoverColor1: "#f7f1e6",
            dropdownMenuBgColor2: "#fef7eb",
            dropdownMenuBgHoverColor2: "#f5eee1",
        }
    },
    {
        title: "Montauk",
        sectionDetails: { title: "light", index: 9 },
        twinTheme: null,
        colorPalette: ["#8EA3BC", "#CACCDC", "#F4E6D9", "#F9F1EA", "#FFFAF3"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FFF9F4",
            secondaryBgColor: "#FFFCF5",
            tertiaryBgColor: "#FCFAF6",
            fgColor1: "167, 177, 194",
            fgColor2: "208, 194, 216",
            sessionBgColor: "#FFFFFC",
            sessionBorderVal: "0.4px solid #E1E1E1",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.02)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F9F6EF",
            hoverColor2: "#F9F5EB",
            hoverColor3: "#fffefa",
            tabColor: "#f3f2ee",
            tabHighlightColor: "#C9BED0",
            headerElementBgColor: "#FFFBF6",
            headerElementBorderVal: "0.6px solid rgba(55, 55, 55, 0.05)",
            headerElementShadow: "0px 6px 7px -3px rgba(0, 0, 0, 0.05)",
            headerElementTextColor: "146, 148, 167",
            tabHighlightBoxShadow: "none",
            headerTimeColor: "#EFC3C8",
            headerProgressColor1: "#BEC7D6",
            headerProgressColor2: "#88909E",
            headerTrackColor1: "#DFD9D2",
            headerTrackColor2: "#ACA596",
            baseProgressColor1: "#A7B7D1",
            baseProgressColor2: "#949EAD",
            baseTrackColor1: "#E0DCD1",
            baseTrackColor2: "#BBB49F",
            progressBallGlow: "none",
            modalBgColor: "#F5F4F1",
            modalBgAccentColor: "#EFEEEC",
            bentoBoxBgColor: "#FBFAF5",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#C3C0D5",
            musicProgressFgColor: "#D0CDE3",
            navMenuBgColor: "#FFFBF5",
            navIconColor: "#C7BDCE",
            navIconBgColor: "#FAF5F0",
            themeToggleBtnBgColor: "#FBF6ED",
            iconToggleBtnBgColor: "#DFCFB7",
            highlighterToggleBtnBgColor: "#FBF6ED",
            midPanelBorder: "none",
            midPanelShadow: "none",            
            midPanelBaseColor: "#F8F1EC",
            midPanelAccentColor1: "#F7F3EE",
            midPanelAccentColor2: "#eae4df",
            midPanelAccentColor3: "#f9f1ea",
            midPanelAccentTextColor: "107, 111, 118",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 2px 12px 7px rgba(0, 0, 0, 0.03)",
            dropdownMenuBgColor1: "#fffaf5",
            dropdownMenuBgHoverColor1: "#F8F4F0",
            dropdownMenuBgColor2: "#fffbf7",
            dropdownMenuBgHoverColor2: "#F8F4F0",
        }
    },
    {
        title: "Sea Foam",
        sectionDetails: { title: "light", index: 10 },
        twinTheme: null,
        colorPalette: ["#A3BECB", "#CED9DE", "#DFE0DC", "#DEC3A9", "#FFFBF4"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: false,
            primaryBgColor: "#FFFBF4",
            secondaryBgColor: "#FFFDF9",
            tertiaryBgColor: "#FCFAF6",
            fgColor1: "177, 196, 205",
            fgColor2: "224, 197, 173",
            sessionBgColor: "#FFFFFC",
            sessionBorderVal: "0.4px solid #E1E1E1",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.02)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F5F5F2",
            hoverColor2: "#F4F3EE",
            hoverColor3: "#F4F4F4",
            tabColor: "#f0f0ef",
            tabHighlightColor: "#CACCDC",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#f8f5ee",
            headerElementBorderVal: "none",
            headerElementTextColor: "155, 167, 173",
            headerElementShadow: "none",
            headerTimeColor: "#E0C5AD",
            headerProgressColor1: "#BEC7D6",
            headerProgressColor2: "#8D97A6",
            headerTrackColor1: "#DFD9D2",
            headerTrackColor2: "#9E9D9B",
            baseProgressColor1: "#B1C4CD",
            baseProgressColor2: "#7E8E95",
            baseTrackColor1: "#E1DBD6",
            baseTrackColor2: "#CAC5B5",
            progressBallGlow: "none",
            modalBgColor: "#f5f5f0",
            modalBgAccentColor: "#EFEFEB",
            bentoBoxBgColor: "#FBFAF5",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#B1C4CD",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#E1E2E0",
            navIconColor: "#FFFBF4",
            navIconBgColor: "#dadcd9",
            themeToggleBtnBgColor: "#FBF6ED",
            iconToggleBtnBgColor: "#DFCFB7",
            highlighterToggleBtnBgColor: "#FBF6ED",
            midPanelBorder: "none",
            midPanelShadow: "0px 3px 8px 1px rgba(0, 0, 0, 0.06)",            
            midPanelBaseColor: "#fbf6ed",
            midPanelAccentColor1: "#F9F5EE",
            midPanelAccentColor2: "#F4F1EA",
            midPanelAccentColor3: "#F4F1EA",
            midPanelAccentTextColor: "100, 97, 91",
            sidePanelBorder: "none",
            sidePanelShadow: "none",
            dropdownMenuBgColor1: "#fffaf5",
            dropdownMenuBgHoverColor1: "#F8F4F0",
            dropdownMenuBgColor2: "#fffcf6",
            dropdownMenuBgHoverColor2: "#F8F5EF",
        }
    },
    {
        title: "Ube",
        sectionDetails: { title: "light", index: 11 },
        twinTheme: { sectionName: "dark", index: 0 },
        colorPalette: ["#636067", "#BEB7C7", "#CACCDC", "#F8EEDB", "#FFFAF3"],
        styling: {
            isDark: false,
            hasTwin: false,
            isHeaderElementTextLight: true,
            primaryBgColor: "#FFFAF0",
            secondaryBgColor: "#FFFCF5",
            tertiaryBgColor: "#FFFDF8",
            fgColor1: "190, 183, 199",
            fgColor2: "220, 202, 155",
            sessionBgColor: "#FFFFFC",
            sessionBorderVal: "0.4px solid #E1E1E1",
            sessionShadowVal: "0px 4px 8px 0px rgba(0, 0, 0, 0.02)",
            textColor1: "67, 63, 50",
            textColor2: "255, 255, 255",
            hoverColor: "#F7F2EA",
            hoverColor2: "#F6F1E9",
            hoverColor3: "#F4EEE4",
            tabColor: "#f2f0ea",
            tabHighlightColor: "#CACCDC",
            tabHighlightBoxShadow: "none",
            headerElementBgColor: "#f7f3e9",
            headerElementBorderVal: "none",
            headerElementTextColor: "139, 132, 110",
            headerElementShadow: "none",
            headerTimeColor: "#DCCA9B",
            headerProgressColor1: "#BEB7C7",
            headerProgressColor2: "#918C96",
            headerTrackColor1: "#E4DFD1",
            headerTrackColor2: "#BEB9AC",
            baseProgressColor1: "#BEB7C7",
            baseProgressColor2: "#98949D",
            baseTrackColor1: "#E5DFCB",
            baseTrackColor2: "#BCB5A0",
            progressBallGlow: "none",
            modalBgColor: "#F9F3E9",
            modalBgAccentColor: "#F2EDE5",
            bentoBoxBgColor: "#FFFAF2",
            bentoBoxBorder: "none",
            bentoBoxShadow: "0px 4px 4px 0px rgba(0, 0, 0, 0.04)",
            muiscPlayerBgColor: "#BEB7C7",
            musicProgressFgColor: "#FFFFFF",
            navMenuBgColor: "#FFFAF3",
            navIconColor: "#B9B3C1",
            navIconBgColor: "#FAF5EB",
            themeToggleBtnBgColor: "#F7F2E7",
            iconToggleBtnBgColor: "#E3DCCD",
            highlighterToggleBtnBgColor: "#F1ECE0",
            midPanelBorder: "none",
            midPanelShadow: "0px 3px 9px 0px rgba(0, 0, 0, 0.04)",            
            midPanelBaseColor: "#faf4e8",
            midPanelAccentColor1: "#FAF3E5",
            midPanelAccentColor2: "#EAE5D5",
            midPanelAccentColor3: "#faf4e7",
            midPanelAccentTextColor: "90, 87, 78",
            sidePanelBorder: "none",
            sidePanelShadow: "0px 2px 17px 7px rgba(0, 0, 0, 0.04)",
            dropdownMenuBgColor1: "#f9f6ed",
            dropdownMenuBgHoverColor1: "#f3efe4",
            dropdownMenuBgColor2: "#fffbf4",
            dropdownMenuBgHoverColor2: "#f8f4ec"
        }
    } as ColorTheme
]
export const imageThemes: ImageTheme[] = [
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg/320px-Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg/2560px-Albert_Bierstadt_-_Indians_Spear_Fishing_-_Google_Art_Project.jpg",
        title: "Indians Spear Fishing",
        artist: "Albert Bierstadt",
        sectionDetails: { title: "image", index: 0 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Home_in_the_Woods_1847_Thomas_Cole.jpeg/320px-Home_in_the_Woods_1847_Thomas_Cole.jpeg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/8/89/Home_in_the_Woods_1847_Thomas_Cole.jpeg",
        title: "Home in the Woods",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 1 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg/320px-Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/9/94/Venice%2C_from_the_Porch_of_Madonna_della_Salute_MET_DP169568.jpg",
        title: "Venice, from the Porch of Madonna della Salute",
        artist: "J.M.W. Turner",
        sectionDetails: { title: "image", index: 2 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_The_Savage_State_1836.jpg",
        title: "Savage State",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 3 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_The_Arcadian_or_Pastoral_State_1836.jpg",
        title: "The Arcadian or Pastoral State",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 4 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg/320px-Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg/2560px-Cole_Thomas_The_Consummation_The_Course_of_the_Empire_1836.jpg",
        title: "Consummation",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 5 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_Destruction_1836.jpg",
        title: "Destruction",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 6 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg/320px-Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg/2560px-Cole_Thomas_The_Course_of_Empire_Desolation_1836.jpg",
        title: "Desolation",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 7 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg/320px-Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg/2560px-Thomas_Cole_-_Dream_of_Arcadia_-_Google_Art_Project.jpg",
        title: "Dream of Arcadia",
        artist: "Thomas Cole",
        sectionDetails: { title: "image", index: 8 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg/320px-Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg/2560px-Ivan_Aivazovsky_-_Ship_on_Stormy_Seas.jpg",
        title: "Ship on Stormy Seas",
        artist: "Ivan Aivazovsky",
        sectionDetails: { title: "image", index: 9 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/500px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg",
        title: "Water Lillies - 1906",
        artist: "Claude Monet",
        sectionDetails: { title: "image", index: 10 }
    },
    {
        thumbnailImgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg/307px-Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg",
        fullImgSrc: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Claude_Monet_-_Waterlilies_-_Google_Art_Project.jpg",
        title: "Waterlilies ",
        artist: "Claude Monet",
        sectionDetails: { title: "image", index: 11 }
    },
    {
        thumbnailImgSrc: "https://pbs.twimg.com/media/Ea2ATpWUwAAwzvR?format=jpg&name=large",
        fullImgSrc: "https://pbs.twimg.com/media/Ea2ATpWUwAAwzvR?format=jpg&name=large",
        title: "Howl's Moving Castle",
        artist: "Studio Gibhli",
        sectionDetails: { title: "image", index: 12 }
    },
    {
        thumbnailImgSrc: "https://wallpapers.com/images/hd/spirited-away-house-on-an-island-hvwghkdhxqbjzprj.webp",
        fullImgSrc: "https://wallpapers.com/images/hd/spirited-away-house-on-an-island-hvwghkdhxqbjzprj.webp",
        title: "Spirited Away",
        artist: "Studio Gibhli",
        sectionDetails: { title: "image", index: 13 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1466350380309-a09bb7347af9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1466350380309-a09bb7347af9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Manhattan Bridge",
        artist: "Hieu Vu Minh (Unsplash)",
        sectionDetails: { title: "image", index: 14 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1451186859696-371d9477be93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1451186859696-371d9477be93?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2673&q=80",
        title: "Prince Regent National Park",
        artist: "NASA (Unsplash)",
        sectionDetails: { title: "image", index: 15 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2711&q=80",
        title: "Space",
        artist: "NASA (Unsplash)",
        sectionDetails: { title: "image", index: 16 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1581610186406-5f6e9f9edbc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1581610186406-5f6e9f9edbc1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Dunes",
        artist: "Daniel Olah (Unsplash)",
        sectionDetails: { title: "image", index: 17 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1644322749926-66ac55e2913e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1644322749926-66ac55e2913e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80",
        title: "Blood Meridian",
        artist: "George Diama (Unsplash)",
        sectionDetails: { title: "image", index: 18 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1538435740860-67bd8f4e8eb8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1538435740860-67bd8f4e8eb8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2728&q=80",
        title: "Foggy Days",
        artist: "Justin Kauffman (Unsplash)",
        sectionDetails: { title: "image", index: 19 }
    },
    {
        thumbnailImgSrc: "https://images.unsplash.com/photo-1532032659282-dc3fe9336831?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=250&q=80",
        fullImgSrc: "https://images.unsplash.com/photo-1532032659282-dc3fe9336831?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80",
        title: "Mt Hood Under the Stars",
        artist: "Clint MCKoy (Unsplash)",
        sectionDetails: { title: "image", index: 9 }
    },
]
export const ambientVideos: VideoTheme[] = [
    {
        title: "Mount Shuksan",
        vidSrc: "https://www.youtube.com/watch?v=qRTVg8HHzUo",
        thumbnailSrc: "https://i.ytimg.com/vi/qRTVg8HHzUo/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCgM2LaUhy3mSWfKCzJ8ysmYiwv6Q",
        channelName: "Nature Soundscapes",
        sectionDetails: { title: "video", index: 0 }
    },
    {
        title: "Hawaii Sunrise",
        vidSrc: "https://www.youtube.com/watch?v=Fz6tH7cTB5M",
        thumbnailSrc: "https://i.ytimg.com/vi/Fz6tH7cTB5M/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCLgi8_QZZUkgV-OntxQ9J2GoJBVA",
        channelName: "Nature Soundscapes",
        sectionDetails: { title: "video", index: 1 }
    },
    {
        title: "Fall Lake",
        vidSrc: "https://www.youtube.com/watch?v=gwE5dGJ_KI0",
        thumbnailSrc: "https://i.ytimg.com/vi/gwE5dGJ_KI0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCCfgYIiku7WbYntiz8YyuV98X13Q",
        channelName: "Nature Soundscapes",
        sectionDetails: { title: "video", index: 2 }
    },
    {
        title: "Rain in Forest",
        vidSrc: "https://www.youtube.com/watch?v=4LeyBbDBvQQ",
        thumbnailSrc: "https://i.ytimg.com/vi/4LeyBbDBvQQ/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBeewEvZCuZSjksjzh1C2C6NUFr4w",
        channelName: "Nature Soundscapes",
        sectionDetails: { title: "video", index: 3 }
    },
    {
        title: "Storm in Forest",
        vidSrc: "https://www.youtube.com/watch?v=XtDwPLk8EgI",
        thumbnailSrc : "https://i.ytimg.com/vi/XtDwPLk8EgI/hqdefault.jpg?sqp=-oaymwE2CNACELwBSFXyq4qpAygIARUAAIhCGAFwAcABBvABAfgB_g6AArgIigIMCAAQARg0IGUoXjAP&rs=AOn4CLAl8f0dt8H-4oi5xHkofaGxvHM-Ng",
        channelName: "Relaxing Ambience ASMR",
        sectionDetails: { title: "video", index: 4 }
    },
    {
        title: "Kapalua Beach, Maui, Hawaii",
        vidSrc: "https://www.youtube.com/watch?v=KM6K6Mz13uA",
        thumbnailSrc: "https://i.ytimg.com/vi/KM6K6Mz13uA/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBbEdwf3JixlHb5E-K_b-zGvtqH0Q",
        channelName: "Nature Soundscapes",
        sectionDetails: { title: "video", index: 5 }
    },
    {
        title: "Study Room with Rain",
        vidSrc: "https://www.youtube.com/watch?v=Jvgx5HHJ0qw",
        thumbnailSrc: "https://i.ytimg.com/vi/Jvgx5HHJ0qw/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAQDhCWJ0TlZkeHq45cZDM4kpPEiA",
        channelName: "Cosmic Report",
        sectionDetails: { title: "video", index: 6 }
    },
    {
        title: "Reading Nook",
        vidSrc: "https://www.youtube.com/watch?v=Ol93KaRhrRM",
        thumbnailSrc: "https://i.ytimg.com/vi/Ol93KaRhrRM/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLDyv-qI-6kRJodCK_4zqvy6l9dYpg",
        channelName: "Cosmic Report",
        sectionDetails: { title: "video", index: 7 }
    },
    {
        title: "Minecraft Calm Ambience",
        vidSrc: "https://www.youtube.com/watch?v=CSk9Ozs5Kpg",
        thumbnailSrc: "https://i.ytimg.com/vi/CSk9Ozs5Kpg/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBOHjSUJP5PevquL2Ms_S2MDboosg",
        channelName: "Craft Therapy",
        sectionDetails: { title: "video", index: 8 }
    },
    {
        title: "Warm hideout duing a Stormy Night",
        vidSrc: "https://www.youtube.com/watch?v=2PywKRQhK2g",
        thumbnailSrc: "https://i.ytimg.com/vi/2PywKRQhK2g/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBW69EqIfsOHOIQf8MsIdWLu6Ozhw",
        channelName: "dreamysound",
        sectionDetails: { title: "video", index: 9 }
    },
    {
        title: "Raining in Osaka",
        vidSrc: "https://www.youtube.com/watch?v=q55qNEKQLG0",
        thumbnailSrc: "https://i.ytimg.com/vi/q55qNEKQLG0/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBPskftIDJ3U7gnbkcBwXcW_urnYQ",
        channelName: "Lofi Music",
        sectionDetails: { title: "video", index: 10 }
    },
]